### ISSUE TITLE
Storage Account Setup needs to be enabled for All Networks

### ISSUE THREAD

**Issue by Dekard** [MicrosoftDocs/dynamics-365-unified-operations-public#4296] opened 2022-11-22 21:12 UTC
Please update this document to point out that currently the Azure Storage account firewall needs to be set to All Networks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Install Export to Azure Data Lake add-in - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake#appid)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by bishalgoswami** [comment] 2022-11-22 21:40
Bug 770436 has been logged to address this issue.

**Comment by Dekard** [comment] 2024-01-18 20:53
@bishalgoswami can we get this updated it's over a year.

**Comment by johnmichalak** [comment] 2024-02-14 18:47
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 18:47 UTC
Labels: bug-created-VSTS

**Comment by Dekard** [comment] 2024-02-14 19:06
It's still an issue F&O does not support Azure Storage account with firewall. You can reproduce it easily by creating a storage account and enabling the Storage Account Firewall.

**Comment by Dekard** [comment] 2024-02-14 19:10
See - Issue here - where customers also point out it only works as ALL Networks - https://learn.microsoft.com/en-us/answers/questions/1340751/azure-storage-account-network-security-when-using
