### ISSUE TITLE
Step 6 the field Type does not exist in RCS

### ISSUE THREAD

**Issue by Stuart-Honour-HCL** [MicrosoftDocs/dynamics-365-unified-operations-public#4546] opened 2023-05-18 10:55 UTC
Create a connected application

1. Sign in to your RCS account.
2. In the Globalization feature workspace, in the Related links section, select Environment setup.
3. On the Environment setup page, on the Action Pane, select Connected applications.
4. Select New to create a connected application.
5. In the Name field, enter the name of the application to connect.
6. In the Type field, select Dynamics 365 Finance.
7. In the Application field, enter the URL of the environment to connect.
8. In the Tenant field, enter the tenant of the environment.
9. Select Save.

**Step 6 the field Type does not exist in RCS**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3197c22f-c401-5af8-ef6e-c6fbcdda4084
* Version Independent ID: 3197c22f-c401-5af8-ef6e-c6fbcdda4084
* Content: [Connected applications - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/e-invoicing-connected-applications)
* Content Source: [articles/finance/localizations/e-invoicing-connected-applications.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/e-invoicing-connected-applications.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @gionoder
* Microsoft Alias: **gionoder**

**Comment by josaw1** [comment] 2023-06-26 22:01
@kfend, can you please investigate?

**Comment by twheeloc** [comment] 2024-02-14 18:40
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-14 18:40 UTC
