### ISSUE TITLE
LCSDiagFX_x64 tool is broken for VHD's and doesn't properly collect environment data.

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/dynamics-365-unified-operations-public#4361] opened 2023-01-03 00:01 UTC
After installing the LCSDiagFX_x64 tool and uploading the certificate to LCS, it fails to collect properly on VHDs using the latest (10.0.29).

After making the below changes to `LCSDiagFXService.exe.config`:

![image](https://user-images.githubusercontent.com/10466466/210285991-f7787997-97db-4b51-9863-cc2e7df2ae1f.png)

It is able to connect, and the environment tile appears in LCS, but after clicking the tile, an error is produced.

![image](https://user-images.githubusercontent.com/10466466/210286048-9f57ef16-4b03-40ef-bbfb-e37884268432.png)

This prevents updates from being identified for the VHD and various other LCS features.

**Comment by twheeloc** [comment] 2024-02-16 15:53
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-16 15:53 UTC
