### ISSUE TITLE
Page is for Russia

### ISSUE THREAD

**Issue by mkowalka** [MicrosoftDocs/dynamics-365-unified-operations-public#4353] opened 2022-12-27 15:56 UTC
Hi, 
This page is under Russia overview, but this is shared feature /scenario. For example, it's valid as well for Poland.
But under Poland overview there is nothing. 

Please correct this and make it available under Europe page like for AX 2012: https://learn.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/eeur-create-a-credit-note-for-correction

Thanks, 
Monika
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df1668d9-587e-48d1-c9af-0bcd75505440
* Version Independent ID: 6303a3a4-120d-47d8-e5e7-e4fa29dadb79
* Content: [Credit note corrections (Russia) - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/rus-credit-note-correction)
* Content Source: [articles/finance/localizations/rus-credit-note-correction.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/rus-credit-note-correction.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by johnmichalak** [comment] 2024-02-14 20:35
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:35 UTC
