### ISSUE TITLE
By default the custom sort order feature is turned off.

### ISSUE THREAD

**Issue by dlanglie** [MicrosoftDocs/dynamics-365-unified-operations-public#4120] opened 2022-08-11 16:06 UTC
https://docs.microsoft.com/en-us/dynamics365/commerce/custom-order-categories-nav-retail-prod-hierarchy
Doc has a note:  

"By default the custom sort order feature is turned off. To learn how to turn on this feature and other features, see [Feature management](https://docs.microsoft.com/en-us/dynamics365/unified-operations/fin-and-ops/get-started/feature-management/feature-management-overview)."

I do not see any feature in Feature Management remotely close to Customer sort order.  I am looking in 10.0.28.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae09d99f-e54d-2e7a-ff26-27a0eb046753
* Version Independent ID: b647704a-868c-307e-9b2b-57231d52ffdd
* Content: [Change the sort order for merchandising entities - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/custom-order-categories-nav-retail-prod-hierarchy)
* Content Source: [articles/commerce/custom-order-categories-nav-retail-prod-hierarchy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/custom-order-categories-nav-retail-prod-hierarchy.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **brshoo**

**Comment by kfend** [comment] 2022-08-15 17:58
@dlanglie - Thank you for the feedback. 
@josaw1 - Can you take a look at this and assign to the correct PM to update? Thanks!

**Comment by dlanglie** [comment] 2022-08-15 18:00
@josaw1<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosaw1&data=05%7C01%7Cdlanglie%40microsoft.com%7Cd812081a31b749fc7cce08da7ee7c902%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637961831220991932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hRFYzGpr5k%2FOPkqIleTEZbCHEjcxLEVq8VrRG2%2Buu0Q%3D&reserved=0>, @Ashish ***@***.***> has already updated the document.

Thank you

**Comment by kfend** [comment] 2022-08-15 18:02
Closing as the issue is resolved.

**Closed by kfend** 2022-08-15 18:02 UTC
Labels: assigned-to-author, doc-bug, triaged-kristin
