### ISSUE TITLE
need more details for limitations on compact layout

### ISSUE THREAD

**Issue by raulmondra28** [MicrosoftDocs/dynamics-365-unified-operations-public#4205] opened 2022-10-03 19:27 UTC
After receiving a case from a customer they are trying to open the reports on compact layout but after reviewing  the code to show that error when it is a mobile layout we found that that functionality is not supported, so please consider to add which are exactly the limitations that compact layout have, thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbad16a9-4173-1fff-ec50-c1d301653973
* Version Independent ID: 34a90d8b-e2be-22d2-49e1-128f235cdf90
* Content: [POS user interface visual configurations - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/pos-screen-layouts)
* Content Source: [articles/commerce/pos-screen-layouts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/pos-screen-layouts.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @boycezhu
* Microsoft Alias: **boycez**

**Comment by bishalgoswami** [comment] 2022-10-04 12:45
Bug 754627 has been logged to address this issue.

**Comment by josaw1** [comment] 2022-10-04 20:52
@boycez can you please review this request?

**Comment by johnmichalak** [comment] 2024-02-14 16:54
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:54 UTC
Labels: bug-created-VSTS
