### ISSUE TITLE
Minimum .NET framework version should be 4.7.2

### ISSUE THREAD

**Issue by KheeChan** [MicrosoftDocs/dynamics-365-unified-operations-public#4146] opened 2022-08-30 19:34 UTC
Minimum .NET framework version should be 4.7.2. See issue 702590 in LCS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe44c05-ed58-b554-859e-2da552dbbd9d
* Version Independent ID: e638edab-dd54-6008-f210-524fd52b0e5b
* Content: [Install the Document Routing Agent to enable network printing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/install-document-routing-agent?source=docs#preparing-to-install-the-document-routing-agent)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/install-document-routing-agent.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment] 2022-08-30 19:42
Bug 744642 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:36
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:36 UTC
Labels: bug-created-VSTS
