### ISSUE TITLE
Overlayering is no longer possible on version 10.*

### ISSUE THREAD

**Issue by TimothyBeachAsurion** [MicrosoftDocs/dynamics-365-unified-operations-public#4234] opened 2022-10-19 21:29 UTC
Please add a clarification to which versions allow overlayering. My understanding is 10.* does not support overlayering. Nothing on this page indication that. This page contradicts the page 2 levels up:

https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/extensibility-home-page

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e561707c-b588-dd5a-6f90-ffa99cc3a824
* Version Independent ID: 8d54840a-d5df-0e5f-2765-dbccf044acce
* Content: [Customize through extension and overlayering - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/customization-overlayering-extensions)
* Content Source: [articles/fin-ops-core/dev-itpro/extensibility/customization-overlayering-extensions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/extensibility/customization-overlayering-extensions.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment] 2022-10-19 22:12
Bug 759261 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:20
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:20 UTC
Labels: bug-created-VSTS
