### ISSUE TITLE
Error on page with JSON element name!

### ISSUE THREAD

**Issue by metkhoo** [MicrosoftDocs/dynamics-365-unified-operations-public#4287] opened 2022-11-18 16:01 UTC
There seems to be an error - but it is not easy to determine which one is in error:

The JSON on this page says an element name is **mshr_ismobilephone**

The TABLE on this same page says the element name is **mshr_ismobile**

Please edit to correct
Many thanks
/Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21f5d0ed-e841-04f9-fa38-1401317ae193
* Version Independent ID: 29cf952c-56c8-13ed-6d16-d9762172863f
* Content: [Party contact - Human Resources | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/human-resources/hr-admin-integration-ats-api-party-contact)
* Content Source: [articles/human-resources/hr-admin-integration-ats-api-party-contact.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/human-resources/hr-admin-integration-ats-api-party-contact.md)
* Service: **dynamics-365-human-resources**
* Product: ****
* Technology: ****
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment] 2022-11-18 18:01
Bug 769768 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:43
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:43 UTC
Labels: bug-created-VSTS
