### ISSUE TITLE
Clarify no public cloud support statement

### ISSUE THREAD

**Issue by rgeal** [MicrosoftDocs/dynamics-365-unified-operations-public#4170] opened 2022-09-16 14:52 UTC
This page states that Dynamics FO (on-prem) is not supported on any public cloud but is it supported on VMC as it's ESXi as the hypervisor? or on Azure/AWS bare-metal offerings?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc242273-ee42-3973-cc47-aece5771ca1f
* Version Independent ID: 0cf0f65b-6187-104a-8228-3c1431225267
* Content: [System requirements for on-premises deployments - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/system-requirements-on-prem?context=%2Fdynamics365%2Fcontext%2Fcommerce)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/system-requirements-on-prem.md)
* Service: ****
* Product: **dynamics-365**
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **peterfriis**

**Comment by PeterRFriis** [comment] 2022-09-19 08:17
Hi
F+O is only supported on dedicated HW, and therefore not on ANY cloud infrastructure. This includes Azure and AWS.
Yes, VMware is supported [based on ](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/setup-deploy-on-premises-pu12#infrastructure).

If you would like to run in the cloud the please consider running our SaaS D365 SCM or Finance offering.

Please let me know if you have any further questions, and I'll be happy to help.
Thanks,
Peter

**Comment by bishalgoswami** [comment] 2022-09-22 09:45
Bug 751248 has been logged to address this issue.

**Comment by rgeal** [comment] 2022-09-23 08:16
Thanks for the follow-up, you mentioned that it is only supported on dedicated HW but offers like dedicated hosts or bare metal on Azure/AWS are dedicated HW, that's why it's still not clear to me. Thanks.

**Comment by johnmichalak** [comment] 2024-02-14 16:43
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:43 UTC
Labels: bug-created-VSTS
