### ISSUE TITLE
target format contains more than one element with the selected name. the configured destinations will be applied to the first occurrence of such elements in the format. consider renaming components to make their names unique.

### ISSUE THREAD

**Issue by vereden** [MicrosoftDocs/dynamics-365-unified-operations-public#4351] opened 2022-12-26 10:37 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20697385-ed83-077e-edd8-8bb51fac0ab8
* Version Independent ID: b72c2777-627a-3ce2-1f7a-59ae94225a3f
* Content: [Electronic reporting (ER) destinations - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/electronic-reporting-destinations)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/electronic-reporting-destinations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/electronic-reporting-destinations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by vereden** [comment] 2022-12-26 10:42
I create a new format , when I try to configure destination I got an error
"target format contains more than one element with the selected name. the configured destinations will be applied to the first occurrence of such elements in the format. consider renaming components to make their names unique."

![image](https://user-images.githubusercontent.com/113829055/209539557-457f92df-c085-4911-bc05-ed64fd89e1b8.png)

![ER eRROR](https://user-images.githubusercontent.com/113829055/209539678-3a92f9a4-90ae-4824-a3a8-b2f1268dccb4.jpg)

**Comment by bishalgoswami** [comment] 2022-12-26 11:15
Bug 776830 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 20:35
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:35 UTC
Labels: bug-created-VSTS
