### ISSUE TITLE
Queries to clarify statements made in this 'Proactive Quality Updates' article

### ISSUE THREAD

**Issue by gphilpott** [MicrosoftDocs/dynamics-365-unified-operations-public#4193] opened 2022-09-28 10:43 UTC
Please can you assist in clarifying statements made in this article? My specific queries are:
1. Please clarify the situation on rollback options - the docs page seems to contain two conflicting statements, which are: (a) _"Customers will still be able to pull the quality updates ahead of proactive deployment if they want._" and (b) _"Can customers delay, reschedule, or pause a quality update? No."_. Which one is correct?
2. Regarding Sandbox sync designation - please can you clarify that where a sandbox exists for the purpose of troubleshooting issues in PRD (i.e. it needs to be on the same version), that this will not be updated automatically? Also will all other sandboxes be updated?
3. Can an exact date be provided for when this rolls out to Production? At the moment the Docs say after November, does this mean after Nov 1st or Nov 30th?
4. Regarding visibility, The article linked for schedule information states 5 days' notice will be provided prior to a proactive update being deployed to a set of environments. As this is not an update that cannot be paused is there any possibility of having more notice? (e.g. 10 days). Also can further information be provided on the time between a proactive quality update being deployed to a Sandbox environment and then the subsequent Production deployment? (to give more time for planning of manual regression testing if not automated capability is ready yet)
5. Please confirm flighting refers to the 'feature flighting' as defined here: [Feature management overview - Finance & Operations | Dynamics 365 | Microsoft Learn](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview#what-is-feature-flighting-and-how-does-it-relate-to-feature-management). Also will this be considered a GA feature that can be controlled via Feature Management or would it require Microsoft to switch to the 'fallback'?
6. Regarding eligibility for an environment to receive an automatic quality update - If a customized package has recently been applied to an environment, applying a quality update automatically close to that time might result in a situation where a regression issue cannot be attributed easily to a particular package - is there any way the automatic update could be sensitive to this (i.e. Not be applied automatically if a custom package is applied, that is not yet deployed to Production). 
Also linked to eligibility to receive an update, does the requirement for priority based scheduling to be active apply to Sandbox environments as well as Production?

Note - this is also posted the LCS Yammer Forums thread that discusses the updates announced regarding this new initiative.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment] 2022-09-28 11:12
Bug 752859 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:51
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:51 UTC
Labels: bug-created-VSTS
