### ISSUE TITLE
LCS / Power Platform Integration / Dual-Write

### ISSUE THREAD

**Issue by karassius** [MicrosoftDocs/dynamics-365-unified-operations-public#4636] opened 2023-07-14 16:04 UTC
Please add information about the availability or unavailability of the Dual-Write function (Power Platform Integration) in the LCS for D365FFO Cloud and OnPrem (LDB) editions

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e31272cf-a87f-0c73-631f-2829cf9ef1ff
* Version Independent ID: e81b0610-320c-eddc-fab2-557685148fc1
* Content: [Comparison of cloud and on-premises features - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/cloud-prem-comparison?source=docs)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/cloud-prem-comparison.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/cloud-prem-comparison.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment] 2023-08-10 11:31
Bug 834375 has been logged to address this issue.

**Comment by josaw1** [comment] 2023-08-10 19:46
@peter-villadsen can you please review?

**Comment by twheeloc** [comment] 2024-02-14 17:53
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-14 17:53 UTC
Labels: bug-created-VSTS
