### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by IanLuu** [MicrosoftDocs/dynamics-365-unified-operations-public#4229] opened 2022-10-19 06:38 UTC
[Enter feedback here]
Hi team,
The section **Create a new workflow type** (https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/workflow-type-create-new#create-a-new-workflow-type-1) I suppose only applies to AX2012, not D365FO. Please revise this to avoid viewer misunderstanding.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 131c2012-9f2c-c128-bb1f-d38d3a4b49ab
* Version Independent ID: 39e85856-e24b-a5c2-e291-4ae514bdea3d
* Content: [Create a new workflow type - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/workflow-type-create-new)
* Content Source: [articles/fin-ops-core/fin-ops/organization-administration/workflow-type-create-new.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/organization-administration/workflow-type-create-new.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **tfehr**

**Comment by bishalgoswami** [comment] 2022-10-19 08:10
Bug 759101 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:08
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:08 UTC
Labels: bug-created-VSTS
