### ISSUE TITLE
The new discount concurrency mode option Always apply is not described. 

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/dynamics-365-unified-operations-public#4118] opened 2022-08-11 12:16 UTC
In this page the new discount concurrency mode option Always apply is not described. What does it do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed31de6-6f28-8607-9537-dc7d7de2fbac
* Version Independent ID: e9f952d3-bbeb-c566-f89d-49a141794807
* Content: [Apply multiple Retail discounts to a product - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/apply-multiple-retail-discounts)
* Content Source: [articles/commerce/Apply-multiple-retail-discounts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/Apply-multiple-retail-discounts.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @shajain
* Microsoft Alias: **shajain**

**Comment by kfend** [comment] 2022-08-15 18:00
@jmeijering - Thank you for the feedback.
@josaw1 - Can you please assign this to the correct PM to update? Thanks!

**Comment by ShalabhjainMSFT** [comment] 2022-08-15 19:19
@josaw1 please assign this to @boycez

**Comment by bishalgoswami** [comment] 2022-08-22 13:13
Bug 734206 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:22
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:22 UTC
Labels: assigned-to-author, doc-enhancement, bug-created-VSTS, triaged-kristin

**Comment by jmeijering** [comment] 2024-02-15 06:41
@johnmichalak when you search for "Always apply" on the page https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/Apply-multiple-retail-discounts the option is still not described. 
Why did you close the call?

**Comment by jmeijering** [comment] 2024-03-04 08:54
@johnmichalak please comment on my remarks of 3 weeks ago
