### ISSUE TITLE
Not Clear on source of customer and vendor VAT numbers

### ISSUE THREAD

**Issue by Dobadino83** [MicrosoftDocs/dynamics-365-unified-operations-public#4283] opened 2022-11-18 09:38 UTC
I raised this via support, and they said we had to comment here.

It's not clear from the page that when you switch on the multiple VAT registrations features that the source of the VAT numbers of customers or suppliers will be the Registrations sections on the address and not the tax exempt number field.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47a12fc-6a0c-9a49-7e4d-76e09ed92ebf
* Version Independent ID: b0ccc044-efa4-6545-7fcf-bd836980653d
* Content: [Reporting for multiple VAT registrations - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-reporting-for-multiple-vat-registrations)
* Content Source: [articles/finance/localizations/emea-reporting-for-multiple-vat-registrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-reporting-for-multiple-vat-registrations.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by bishalgoswami** [comment] 2022-11-18 10:00
Bug 769687 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:41
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:41 UTC
Labels: bug-created-VSTS
