### ISSUE TITLE
Please Add to DRA FAQ - how to change the DRA URL.

### ISSUE THREAD

**Issue by JOLSO** [MicrosoftDocs/dynamics-365-unified-operations-public#4465] opened 2023-03-09 17:55 UTC
[Please add instructions to change the URL in the FAQ area. I found the instructions here -https://community.dynamics.com/365/financeandoperations/f/dynamics-365-for-finance-and-operations-forum/364600/how-to-change-url-in-document-routing-agent#:~:text=You%20can%20modify%20URL%20after%20signing%20out%20in,field%20should%20get%20enabled%20now%20to%20modify.%20Reply ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1745c96-57e0-956f-a5cc-dda604e34d7f
* Version Independent ID: 0209d62f-88de-ea09-ac08-a0d5ba8397ae
* Content: [Run the Document Routing Agent as a Windows service - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/run-document-routing-agent-as-windows-service?source=docs)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/run-document-routing-agent-as-windows-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/run-document-routing-agent-as-windows-service.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment] 2023-03-09 18:32
Bug 797273 has been logged to address this issue.

**Comment by w-azure** [comment] 2024-04-09 21:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by w-azure** 2024-04-09 21:23 UTC
Labels: bug-created-VSTS, kfm-fx-devit
