### ISSUE TITLE
Cannot Extend DimensionEssentials

### ISSUE THREAD

**Issue by steevegilbert** [MicrosoftDocs/dynamics-365-unified-operations-public#145] opened 2018-05-30 12:42 UTC
Is it just me or we cannot extend DimensionEssentials?  The only option is to customize.  We're running 1611.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6606b52c-677f-bf60-880d-3ec4dd03fb36
* Version Independent ID: 75150ec2-39e8-64e9-524e-798a2c480bd0
* Content: [Make a backing table be consumable as a Financial dimension - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimensionable-entities)
* Content Source: [articles/dev-itpro/financial/dimensionable-entities.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/financial/dimensionable-entities.md)
* Service: **dynamics-ax-platform**
* Product: **unspecified**
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by dfroslieMSFT** [comment] 2018-05-30 21:32
I assume you are referring to the Security Privilege, DimensionEssentials, Steve.  Security privileges are not extensible by design, although roles and duties are extensible.

**Comment by MargoC** [comment] 2018-05-30 22:09
Closing this issue. Please let us know if it isn't clear.

**Closed by MargoC** 2018-05-30 22:09 UTC
Labels: assigned-to-author, product-question, triaged

**Comment by steevegilbert** [comment] 2018-05-31 12:22
Yes, I was referring to the Security Privilege.  So in the topic "[make a backing table be consumable as a Financial Dimension](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/financial/dimensionable-entities)", step 1.14, since DimensionEssentials cannot be extended you tell us that we have to do a customization?  What confuses me is that it cannot be done with the latest version since it's "Hard Sealed".  Every changes as to be an extension.

**Comment by dfroslieMSFT** [comment] 2018-05-31 19:56
Thanks for the details, Steve.  I'm going to need to do some follow up on this.  I will get back to you as soon as I have a better answer... early next week at the latest.

**Comment by dfroslieMSFT** [comment] 2018-06-12 17:45
Apologies for the delay here, but I don't have a final recommendation on this.  Thanks for your patience.
