### ISSUE TITLE
Update initializeReportControl to initializeReportControl V2

### ISSUE THREAD

**Issue by kulahad** [MicrosoftDocs/dynamics-365-unified-operations-public#4490] opened 2023-04-04 04:47 UTC
Hello MS Docs,

I believe this method has been deprecated and has been replaced by `initializeReportControlV2` but there isn't any note or reference about the new method.
It might be confusing for the people who might be studying for the Certification exams.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58543120-6ce0-15a0-dd0a-ca4888b11d85
* Version Independent ID: 4e804992-b8bd-e312-eb85-da4b25f9d3cd
* Content: [Add analytics to workspaces by using Power BI Embedded - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/add-analytics-tab-workspaces.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment] 2023-04-04 06:36
Bug 802661 has been logged to address this issue.

**Comment by w-azure** [comment] 2024-04-09 21:24
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by w-azure** 2024-04-09 21:24 UTC
Labels: bug-created-VSTS, kfm-fx-devit
