### ISSUE TITLE
More and better details would be nice to have

### ISSUE THREAD

**Issue by klofskar** [MicrosoftDocs/dynamics-365-unified-operations-public#4336] opened 2022-12-19 10:59 UTC
Hello

The content of this page is very good. However, I think it would be beneficial for learning purposes to have more detailed screen shots, for example in the picture below, that shows a better overview of the window and also to see on example of how the setupt could be done. 

I also would like to see the link to the TechTalk series about this subject as part of this learning section.

To add Q/A if available would also be a good thing have  in learning, or at least a link to community.dynamics.com where to find more info in the many details in this part. 

![image](https://user-images.githubusercontent.com/100188828/208410469-7e0fab86-f426-4282-aba2-66d95bb47256.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fad59b08-93b4-a4e7-471c-2d5043afdc48
* Version Independent ID: fad59b08-93b4-a4e7-471c-2d5043afdc48
* Content: [Prepare your environment to interoperate with ID-porten and Altinn web services - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-nor-vat-return-setup)
* Content Source: [articles/finance/localizations/emea-nor-vat-return-setup.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-nor-vat-return-setup.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by johnmichalak** [comment] 2024-02-14 20:24
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:24 UTC
