### ISSUE TITLE
Compensation? How about Offset/Netting?

### ISSUE THREAD

**Issue by LodRose** [MicrosoftDocs/dynamics-365-unified-operations-public#4125] opened 2022-08-17 00:18 UTC
[When we speak of compensation, it is usually in relation to salary, reimbursement and such. Shouldn't Offset/Netting be a better label for these types of transactions?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c85d41a-3795-ac2a-19fc-a1d3ce57b603
* Version Independent ID: 5b00762f-63ff-50e9-d9b6-4323e5e0ee27
* Content: [Set up customer and vendor compensation - Finance | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/finance/localizations/emea-compensation-customer-vendor-transactions#feedback)
* Content Source: [articles/finance/localizations/emea-compensation-customer-vendor-transactions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-compensation-customer-vendor-transactions.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @mrolecki
* Microsoft Alias: **mrolecki**

**Comment by twheeloc** [comment] 2022-08-17 17:53
@LodRose, thank you for the feedback.
@mrolecki, please review the feedback and update the content as needed.

**Comment by johnmichalak** [comment] 2024-02-14 16:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:23 UTC
Labels: assigned-to-author, doc-enhancement, triaged - tammy
