### ISSUE TITLE
Delivery schedule and intercompany

### ISSUE THREAD

**Issue by mbinaisseMs** [MicrosoftDocs/dynamics-365-unified-operations-public#4182] opened 2022-09-23 08:21 UTC
We should add that Delivery Schedule is not compatible with intercompany SO/PO

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2ae63b9-273b-9ed0-328f-4ed2accc2068
* Version Independent ID: 5e935a45-c5ea-0ff0-2b9e-52ef28135dd2
* Content: [Delivery schedules - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/delivery-schedules)
* Content Source: [articles/supply-chain/sales-marketing/delivery-schedules.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/sales-marketing/delivery-schedules.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Henrikan
* Microsoft Alias: **henrikan**

**Comment by bishalgoswami** [comment] 2022-09-23 09:47
Bug 751725 has been logged to address this issue.

**Comment by bishalgoswami** [comment] 2022-09-23 11:47
Bug 751736 has been logged to address this issue.

**Comment by bishalgoswami** [comment] 2022-09-23 13:48
Bug 751744 has been logged to address this issue.

**Comment by bishalgoswami** [comment] 2022-09-23 15:48
Bug 751854 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:49
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:49 UTC
Labels: bug-created-VSTS
