### ISSUE TITLE
Quarantine orders no longer supported for warehouse management processes (Sales return page)

### ISSUE THREAD

**Issue by mmrauta** [MicrosoftDocs/dynamics-365-unified-operations-public#4109] opened 2022-08-05 14:24 UTC
Since version 10.0.25, as part of the bug fix, the quarantine orders have been disabled for warehouse management processes.
In this article it is written that they are supported for return order which is not true anymore. Moreover, the pallet transport is not supported anymore, so the following fragment from the **Arrival at the warehouse for inspection** section makes no sense anymore:

> If you're using Warehouse management, generate pallet transports. The return line will have a status of Arrived during pallet transport.

Please notice there is a similar problem with another docs. I have created also this issue: 
[#4108](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/4108)

If you need more information, please contact me (Microsoft alias: mprazanowska)
Best regards,
Marta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337291e2-594f-cb78-318b-a7ab5b4d0b5c
* Version Independent ID: dc7a36d5-e4f8-fbf9-ef03-09077706c3ea
* Content: [Sales returns - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/warehousing/sales-returns#arrival-at-the-warehouse-for-inspection)
* Content Source: [articles/supply-chain/warehousing/sales-returns.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/warehousing/sales-returns.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @Mirzaab
* Microsoft Alias: **mirzaab**

**Comment by johnmichalak** [comment] 2022-08-05 15:34
@mmrauta Thank you for the feedback.

@Mirzaab  Please take a look at the suggestion and update the article as appropriate.

**Comment by KendalBond007** [comment] 2023-10-05 20:21
@Mirzaab - Following up: any additional work needed on this, or can we slate it to close?

@josaw1
@johnmichalak

**Comment by johnmichalak** [comment] 2024-02-14 16:19
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:19 UTC
Labels: assigned-to-author, triaged-john
