### ISSUE TITLE
Feature enablement cannot check

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [MicrosoftDocs/dynamics-365-unified-operations-public#4207] opened 2022-10-05 02:36 UTC
In section "How can feature enablement be checked in code?", there's a sample code using 'BatchContentionPreventionFeature::instance()', but it returns error with message "The method 'instance' contained in the non-public class 'BatchContentionPreventionFeature' is inaccessible.".
Please fix this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51e63496-19e3-182e-c19d-027a0a5f6acf
* Version Independent ID: c8a51a1e-25e8-fbe3-4580-baca9046b7b0
* Content: [Feature management overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview#how-can-feature-enablement-be-checked-in-code)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/feature-management/feature-management-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment] 2022-10-05 02:46
Bug 755797 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:55
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:55 UTC
Labels: bug-created-VSTS
