### ISSUE TITLE
For the select query using SysDa, it can be built using SysDaQueryObjectBuilder. It would be better to include it in the document.

### ISSUE THREAD

**Issue by peter-xu** [MicrosoftDocs/dynamics-365-unified-operations-public#4466] opened 2023-03-10 02:25 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2888e11c-17de-f90c-a48e-409baee04833
* Version Independent ID: b6f71c61-469e-46d8-9a7f-7cc5da547850
* Content: [Access data by using the SysDa classes - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/sysda)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-ref/sysda.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-ref/sysda.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by bishalgoswami** [comment] 2023-03-10 02:33
Bug 797372 has been logged to address this issue.

**Comment by josaw1** [comment] 2023-03-13 18:46
@johnmichalak can you please look into this? Thank you!

**Comment by w-azure** [comment] 2024-04-09 21:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by w-azure** 2024-04-09 21:23 UTC
Labels: bug-created-VSTS, kfm-fx-devit
