### ISSUE TITLE
Configure fiscal books

### ISSUE THREAD

**Issue by betespadula** [MicrosoftDocs/dynamics-365-unified-operations-public#4348] opened 2022-12-23 15:36 UTC
[Enter feedback here]
review all the setups informed of the generation of Fiscal books obligations (SPEDs, GIA), as they are wrong. Check AX2012R3 document that is more correct: https://learn.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/bra-setting-up-fiscal-books

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 184a817b-aeb1-b99c-8cfc-f2c57437917c
* Version Independent ID: 31f767aa-6d36-41d7-2cb5-dc97911ec60e
* Content: [Configure fiscal books - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/latam-bra-configure-fiscal-books)
* Content Source: [articles/finance/localizations/latam-bra-configure-fiscal-books.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/latam-bra-configure-fiscal-books.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @v-gonode
* Microsoft Alias: **kfend**

**Comment by johnmichalak** [comment] 2024-02-14 20:31
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:31 UTC
