### ISSUE TITLE
Not clear whether RPO is 15 minutes or few seconds

### ISSUE THREAD

**Issue by toghe** [MicrosoftDocs/dynamics-365-unified-operations-public#4310] opened 2022-12-02 15:42 UTC
[Enter feedback here]

Cfr following paragraph:

_In the event of an unanticipated region-wide outage, such as a natural disaster that affects the whole Azure region, and if Microsoft has determined that the region won't become available within a reasonable amount of time, Microsoft will notify customers and switch over the traffic so that it's routed to the secondary region instances. In these cases, customers might experience up to 15 minutes of data loss, depending on the nature and timing of the outage. RPO is small: up to a few seconds or a couple of minutes._

The last 2 sentences seem contradictory. Data loss and RPO are the same thing.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 496ab166-952c-1325-4132-f680af468674
* Version Independent ID: 7ab562ca-bd56-ce01-0df2-d1a6fd244c05
* Content: [Business continuity and disaster recovery - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/business-continuity-disaster-recovery.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @MicroSri
* Microsoft Alias: **sriknair**

**Comment by bishalgoswami** [comment] 2022-12-02 15:51
Bug 772465 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 18:59
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 18:59 UTC
Labels: bug-created-VSTS
