### ISSUE TITLE
Architecture picture

### ISSUE THREAD

**Issue by Anders-Dahlin** [MicrosoftDocs/dynamics-365-unified-operations-public#4413] opened 2023-02-01 17:01 UTC
I would recommend adding another/better picture of the architecture. 

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0469cd8-7247-0523-4e91-1cc0ad4d3516
* Version Independent ID: f2787488-34df-5b50-6b73-08fd992e697c
* Content: [Finance and operations application architecture - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/imp-lifecycle/architecture-overview?context=%2Fdynamics365%2Fcontext%2Fsupply-chain)
* Content Source: [articles/fin-ops-core/fin-ops/imp-lifecycle/architecture-overview.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/imp-lifecycle/architecture-overview.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @abunduc-ms
* Microsoft Alias: **abunduc**

**Comment by bishalgoswami** [comment] 2023-02-01 18:20
Bug 788147 has been logged to address this issue.

**Comment by abunduc-ms** [comment] 2023-02-02 08:52
@Anders-Dahlin can you please provide more details? What are the expectations?

**Comment by Anders-Dahlin** [comment] 2023-02-02 09:59
A bit more details on the architecture of Dynamics 365 “Finance and operations”.

Do we have something that’s one more level down thank just one box. How it all connects.

If available to describe the solution to customers solution architects.

Thanks

**Comment by johnmichalak** [comment] 2024-04-10 20:02
Reached out to PM for guidance.

**Comment by johnmichalak** [comment] 2024-04-11 19:44
PM has confirmed this issue should be closed as the article is current and intended to only provide an overview and not detailed inner workings on the architecture.

**Closed by johnmichalak** 2024-04-11 19:44 UTC
Labels: bug-created-VSTS, triaged-john
