### ISSUE TITLE
Unable to create "ADFSServerApplicationForRetail" CommandNotFoundException.

### ISSUE THREAD

**Issue by Junaidahm3d** [MicrosoftDocs/dynamics-365-unified-operations-public#879] opened 2019-02-06 08:41 UTC
Need Help..!

I am stuck at point 6, where I need to create **"ADFSServerApplicationForRetail"**.

6. On the ADFS machine currently viewing, run this script in a new PowerShell window using the command **.\Create-ADFSServerApplicationForRetail -HostUrl 'ax.d365ffo.onprem.contoso.com',** where the HostUrl value can be found in Service Fabric. To find the HostUrl value, navigate to Service Fabric > Application fabric:/AXSF > Details > Aad_AADValidAudience.

--x--

PS C:\scripts> .\Create-ADFSServerApplicationForRetail -HostUrl 'https://ax.dynamics.dax365.com'
New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl : The term
'New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.

PSMessageDetails      : 
Exception             : System.Management.Automation.CommandNotFoundException: The term 
                        'New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl' is not recognized as the name of a 
                        cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
                        path was included, verify that the path is correct and try again.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl
CategoryInfo          : ObjectNotFound: (New-D365FOAdfsS...ostUrl:$HostUrl:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\scripts\Create-ADFSServerApplicationForRetail.ps1: line 51
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

-- x --

Environment Details:
Environment version information
Application release 8.1 (8.1.195.20006)
Platform release Update22 (7.0.5095.41329)

I have also tried to run the command on another environment and other than ADFS machine but face the same issue.
Regards,

Junaid Ahmed

**Comment by sericks007** [comment] 2019-02-06 15:21
Can you please let me know which article you were viewing?  If you could provide the URL of the article, that will help me direct this issue to the appropriate person.

**Comment by Junaidahm3d** [comment] 2019-02-07 11:04
> Can you please let me know which article you were viewing? If you could provide the URL of the article, that will help me direct this issue to the appropriate person.

Thanks Sally for your time, actually the issue is from infrastructure script.

"Create-ADFSServerApplicationForRetail.ps1." line 51 where 'New-D365FOAdfsServerApplicationForRetail-HostUrl:$HostUrl' is incorrect.  I have added a space between ApplicationForRetail and -HostUrl. 

URL: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/deploy-retail-onprem

**Comment by sericks007** [comment] 2019-02-07 14:22
Glad the issue is resolved!  I'll close this issue now.

**Closed by sericks007** 2019-02-07 14:22 UTC
Labels: needs-more-info
