### ISSUE TITLE
Electronic Messages page access issue

### ISSUE THREAD

**Issue by RalucaLucia** [MicrosoftDocs/dynamics-365-unified-operations-public#4212] opened 2022-10-07 10:11 UTC
Hi Team,

Can you please add on the page the next information:
In order for the users to be able to access and edit the Electronic messages page, the sys admin has to add the user role under Electronic message processing page. If the role is not added in there, the user can only open the page, but he/she cannot see any information and cannot edit.
Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc14827-9eeb-2fa5-3dd9-6fbe8a054ec2
* Version Independent ID: a7c893fa-8da4-8e5c-dbf0-d897fb542c60
* Content: [Electronic messaging - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/general-ledger/electronic-messaging)
* Content Source: [articles/finance/general-ledger/electronic-messaging.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/general-ledger/electronic-messaging.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by bishalgoswami** [comment] 2022-10-07 10:49
Bug 756585 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:58
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:58 UTC
Labels: bug-created-VSTS
