### ISSUE TITLE
API to check operation conditions

### ISSUE THREAD

**Issue by RGFAva** [MicrosoftDocs/dynamics-365-unified-operations-public#4613] opened 2023-06-27 07:16 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9164e9f-178d-835e-0305-e95c449e04dd
* Version Independent ID: 8c2f234f-027d-e066-d3ce-460f2378c567
* Content: [Product configuration overview - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/pim/build-product-configuration-model)
* Content Source: [articles/supply-chain/pim/build-product-configuration-model.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/pim/build-product-configuration-model.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by bishalgoswami** [comment] 2023-08-10 11:32
Bug 834389 has been logged to address this issue.

**Comment by twheeloc** [comment] 2024-02-14 18:37
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-14 18:37 UTC
Labels: bug-created-VSTS
