### ISSUE TITLE
Missing overview for possible filters

### ISSUE THREAD

**Issue by SysC0mp** [MicrosoftDocs/dynamics-365-unified-operations-public#4274] opened 2022-11-11 15:31 UTC
There is no information anywhere on possible filter values. 

For example: 
I want to filter for a specific label file, which type do I need to use? type:"labelfile" isn't working

Please add a legend with all possible filter options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8320da9e-599b-0584-ea08-59bf8afffc98
* Version Independent ID: 76120ced-276f-bc16-9c03-c1ac3b189be6
* Content: [Application Explorer - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/application-explorer)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/application-explorer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/application-explorer.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @gianugo
* Microsoft Alias: **gianura**

**Comment by bishalgoswami** [comment] 2022-11-16 03:48
Bug 768913 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:37
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:37 UTC
Labels: bug-created-VSTS

**Comment by SysC0mp** [comment] 2024-04-08 10:43
@johnmichalak I don't understand this response. There is nothing to reproduce as this is clearly no issue, I am just asking to add relevant but missing information to the official documentation of the product. As a developer, you have no information available  anywhere on how to filter for certain types in the application explorer. I also added an easy to understand example in my description above. Please add a legend with detailed information on this topic. 

For example: Appliation explorer -> Filter by type -> What are the supported values to filter here? 

How can I reopen this?
