### ISSUE TITLE
KV "Access Control" permissions

### ISSUE THREAD

**Issue by DaveDaiker** [MicrosoftDocs/dynamics-365-unified-operations-public#4479] opened 2023-03-24 16:28 UTC
In the "Authorize the application to read secrets in the key vault" you need to describe the needed rights if the KV is using "Azure role-based access control" permissions model.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c84e15d4-bcac-038a-2b1e-8c456ee25bd9
* Version Independent ID: 478b5f33-f745-1df2-8fe0-da9e64233165
* Content: [Install Export to Azure Data Lake add-in - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/configure-export-data-lake.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by bishalgoswami** [comment] 2023-03-24 17:53
Bug 800521 has been logged to address this issue.

**Comment by twheeloc** [comment] 2024-02-14 21:19
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-14 21:19 UTC
Labels: bug-created-VSTS
