### ISSUE TITLE
Generate packing slip

### ISSUE THREAD

**Issue by mkowalka** [MicrosoftDocs/dynamics-365-unified-operations-public#4357] opened 2022-12-30 11:37 UTC
There is missing information how to generate the packing slip. 

There is only info how to view this under inquires. 

As far as I know, we can generate the packing slip from Periodic task > Warehouse transfer

Please update the learn page with necessary details. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29a9e46e-a5a5-dfc3-b038-6bb15caec899
* Version Independent ID: 82a6acd6-ec07-e12f-b5e6-f31974fcb83f
* Content: [LT-00003 Generate a fixed asset transfer between warehouses document - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/tasks/lt-00003-fixed-asset-transfer)
* Content Source: [articles/finance/localizations/tasks/lt-00003-fixed-asset-transfer.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/tasks/lt-00003-fixed-asset-transfer.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by johnmichalak** [comment] 2024-02-14 20:38
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:38 UTC
