### ISSUE TITLE
Deprecated feature?

### ISSUE THREAD

**Issue by mpburtt** [MicrosoftDocs/dynamics-365-unified-operations-public#4282] opened 2022-11-17 15:18 UTC
This page seems to document LCS features that are no longer available. Were they lost in August when the Configuration and Data Manager functionality were removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da1ee1f9-6624-ffbb-70a5-d275c0cf4c62
* Version Independent ID: 48f53ecb-a716-e17b-8939-63b669176e73
* Content: [Process and consume data packages in finance and operations apps - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions)
* Content Source: [articles/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/lcs-solutions/process-data-packages-lcs-solutions.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment] 2022-11-18 08:00
Bug 16316636 has been logged to address this issue.

**Comment by sericks007** [comment] 2022-11-18 12:45
@josaw1, please assign to the appropriate person.

**Comment by josaw1** [comment] 2022-11-18 18:32
@mpburtt, thank you for the comment.  @laneswenka can you please review this article and update as needed?

**Comment by johnmichalak** [comment] 2024-02-14 17:41
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:41 UTC
Labels: assigned-to-author, doc-bug, bug-created-VSTS
