### ISSUE TITLE
Maintanance mode is triggering DB Sync

### ISSUE THREAD

**Issue by xDynaMike** [MicrosoftDocs/dynamics-365-unified-operations-public#4142] opened 2022-08-26 10:20 UTC
I think it is worth to add to this page that when you turn off the Maintanance mode then DB Sync is triggered - it's a simple solution for a case where the customer is suspecting that DB Sync went well (no errors) but for example for some reason deleted field is still there in table schema.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ae449b-ec59-28d4-1934-6909e77ee4f3
* Version Independent ID: df6ae442-3466-4c69-aa11-ed35e20a629f
* Content: [Maintenance mode - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/maintenance-mode)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/sysadmin/maintenance-mode.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment] 2022-08-26 11:37
Bug 735508 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:35
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:35 UTC
Labels: bug-created-VSTS
