### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by SAPVCOL** [MicrosoftDocs/dynamics-365-unified-operations-public#4311] opened 2022-12-06 12:05 UTC
Hi, 

Is it possible to get notifications on dualwrite updates via email?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8043d72-1496-a79a-da5b-60dc1d24f561
* Version Independent ID: fa5f09b6-10d9-ab9a-6f65-da69252777c1
* Content: [What's new or changed in dual-write - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/whats-new-dual-write.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by johnmichalak** [comment] 2024-02-14 20:11
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:11 UTC
Labels: bug-created-VSTS
