### ISSUE TITLE
EU sales list / intrastat  Currency definition

### ISSUE THREAD

**Issue by anboudin** [MicrosoftDocs/dynamics-365-unified-operations-public#4471] opened 2023-03-21 05:13 UTC
If multi VAT ID is enable, multi countries may requested intrastat / EU sales list. But they will then have different currency code (as EUR / SEK / CHF...)
Intrastat and EU sales list should then be reported on country currency. 
this information comes from Foreign trade parameters / country/regions. But in MS document this is not mentioned.

customer reported that it is missing information on MS document.

could we add that currency from foreign trade parameters / country/region properties will define the report currency?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47a12fc-6a0c-9a49-7e4d-76e09ed92ebf
* Version Independent ID: b0ccc044-efa4-6545-7fcf-bd836980653d
* Content: [Reporting for multiple VAT registrations - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/emea-reporting-for-multiple-vat-registrations)
* Content Source: [articles/finance/localizations/emea-reporting-for-multiple-vat-registrations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/emea-reporting-for-multiple-vat-registrations.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @AdamTrukawka
* Microsoft Alias: **atrukawk**

**Comment by josaw1** [comment] 2023-03-28 20:14
Thanks for the feedback. @kfend can you please review?

**Comment by kfend** [comment] 2023-03-28 20:19
@liza-golub - Can you please take a look at this article and update as needed? Thank you!

**Comment by w-azure** [comment] 2024-04-09 21:24
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by w-azure** 2024-04-09 21:24 UTC
Labels: doc-enhancement, triaged-Jo, kfm-fx-devit
