### ISSUE TITLE
Ensure the alert batch jobs are running

### ISSUE THREAD

**Issue by DianeMBrock** [MicrosoftDocs/dynamics-365-unified-operations-public#4233] opened 2022-10-19 16:40 UTC
The user configured to execute the Alert batch jobs needs to have RunAs privileges setup on the Active Directory Domain.  This is needed because each rule is executed in the context of the user that created it. This ensures that the user creating the rule meets the security requirements needed to view the data returned from the form query. It prevents unauthorized access to the data in the case of a user changing roles.  Failure to configure a user with the RunAs privilege may result in unintended authorization failures that can lead to unwanted AOS restarts.

The user executing the Alert batch jobs must also be able to send email in the event the rule is configured to send an email notification.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff6f2d2-3ff9-6e7d-999f-1da5ecf248ab
* Version Independent ID: 3f877db5-f3de-6ed3-0f8e-94b8361e444a
* Content: [Create alert rules - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/create-alerts)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/create-alerts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/create-alerts.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment] 2022-10-19 18:11
Bug 759226 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:14
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:14 UTC
Labels: bug-created-VSTS
