### ISSUE TITLE
Moving LCS implementation projects from on-premises to the cloud

### ISSUE THREAD

**Issue by abueiddev** [MicrosoftDocs/dynamics-365-unified-operations-public#4356] opened 2022-12-29 16:12 UTC
We used this tool to migrate on-premises to cloud as instructed by MS support, the migration was completed successfully but we had an issue while trying to open the about form (SysAbout), the issue was solved by creating the missing views (UTILELEMENTS , UtilGranularLayers) in the cloud UAT database.

the mentioned views exist in the on-premises database but for some reason were not replicated in the cloud database.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42eeda26-b0da-fe66-ef03-a26dbf16d923
* Version Independent ID: 5cb45351-842a-b98b-1120-6eb2f657fe47
* Content: [Upgrade from AX 2012 - Data upgrade in self-service environments - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service)
* Content Source: [articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/migration-upgrade/data-upgrade-self-service.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @veeravendhan-s
* Microsoft Alias: **vesakkar**

**Comment by bishalgoswami** [comment] 2022-12-29 17:28
Bug 777255 has been logged to address this issue.

**Comment by josaw1** [comment] 2023-01-03 23:11
@laneswenka please review.

**Comment by johnmichalak** [comment] 2024-02-14 20:37
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:37 UTC
Labels: bug-created-VSTS
