### ISSUE TITLE
We should be able to see easily when Non Compliances are linked to a PO line

### ISSUE THREAD

**Issue by LGERMES** [MicrosoftDocs/dynamics-365-unified-operations-public#4632] opened 2023-07-13 14:17 UTC
One should be able to see whether there is a non compliance created on a Purchase Orde Line (and other lines likely to suffer from non compliance). Either by a checkbox ( "Non Compliance linked" for example, marking if there is at least one non compliance related to that line). There is not such attributes currently on the PO lines; We need to open the associated Non Compliances to find the line(s) for which a NC was open.

https://learn.microsoft.com/fr-fr/dynamics365/supply-chain/inventory/tasks/create-process-non-conformance

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8244919c-5eba-1b67-8872-6d30ba096297
* Version Independent ID: 8d6f54ac-3c59-8195-74e8-63e764bbfb12
* Content: [Create and process nonconformances - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/tasks/create-process-non-conformance?source=docs)
* Content Source: [articles/supply-chain/inventory/tasks/create-process-non-conformance.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/tasks/create-process-non-conformance.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by bishalgoswami** [comment] 2023-08-10 11:31
Bug 834379 has been logged to address this issue.

**Comment by twheeloc** [comment] 2024-02-14 17:57
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-14 17:57 UTC
Labels: bug-created-VSTS
