### ISSUE TITLE
Confusing or incorrect information

### ISSUE THREAD

**Issue by agusriy** [MicrosoftDocs/dynamics-365-unified-operations-public#4340] opened 2022-12-20 15:07 UTC
In this page, to identify what fixes went to PQU it says:

_In the exported file, filter and select the Build version that is less than or equal to build number 10.0.1265.89. You should now be able to see the delta payload._

When we click on View Update, it will show all quality updates that the current environment does not have, so all the versions are higher and those updates that went in the system no longer can be seen there.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment] 2022-12-20 17:03
Bug 776107 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 20:26
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:26 UTC
Labels: bug-created-VSTS
