### ISSUE TITLE
Your guide needs an update

### ISSUE THREAD

**Issue by GeorgeSasDK** [MicrosoftDocs/dynamics-365-unified-operations-public#3041] opened 2020-12-19 21:35 UTC
Your guide has a flaw and the section "Update the LocalAgent certificate" needs to be revised.

In the section "Activate new certificates within Service Fabric cluster" we upgrade the clusterconfig.json with the new certificates and we also perform a ServiceFabricClusterConfigurationUpgrade. Thus the certificates on the cluster WILL be updated here in this section.
So when we update the localagent with this command ".\LocalAgentCLI.exe Cleanup <path of localagent-config.json> " and we DO NOT update the WCF/SOAP thumbprint (if that is what we rotate) we will receive an error.

LocalAgentCLI.exe Error: 0 : Exception System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricServerAuthenticationFailedException: **FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched** ---> System.Runtime
.InteropServices.COMException: Exception from HRESULT: 0x80071C44
   at System.Fabric.Interop.NativeClient.IFabricQueryClient11.EndGetApplicationList2(IFabricAsyncOperationContext context)
   at System.Fabric.FabricClient.QueryClient.GetApplicationListAsyncEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SetupInfrastructure.ServiceFabricApplicationSetupManager`1.<DeleteApplication>d__29.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at LocalAgentCLI.Program.Main(String[] args)
---> (Inner Exception #0) System.Fabric.FabricServerAuthenticationFailedException: FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C44
   at System.Fabric.Interop.NativeClient.IFabricQueryClient11.EndGetApplicationList2(IFabricAsyncOperationContext context)
   at System.Fabric.FabricClient.QueryClient.GetApplicationListAsyncEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SetupInfrastructure.ServiceFabricApplicationSetupManager`1.<DeleteApplication>d__29.MoveNext()<---

**So I think you should specify here that the NEW certificate thumbprints must be used in order to cleanup the local agent.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac091f6-4eb0-3174-d8ae-79ee922349a8
* Version Independent ID: b141a04f-324d-9050-59c8-2a761a99bdab
* Content: [Certificate rotation - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem#cleanupoldsfcerts)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/deployment/certificate-rotation-on-prem.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @PeterRFriis
* Microsoft Alias: **perahlff**

**Comment by RobinARH** [comment] 2020-12-21 20:05
@PeterRFriis - Can you take a look? Thanks.

**Comment by PeterRFriis** [comment] 2021-01-07 09:15
Hi @GeorgeSasDK 
I may be misunderstanding your comment. But if you follow the documentation and update the SF cert, then the new should be added as a new cert and the old should stay as a secondary. When this is setup correctly then the LocalAgent clean up should be able to communicate with the SF cluster, as the secondary is still valid.

If the SF cluster cert has completely expired, then the situation is different, and the documentation breaks of into a redeployment of the cluster.

So for now I do not see a flaw in the docs, but if needed please elaborate on your process and situation where this occurred.

Thank you.
Peter

**Comment by GeorgeSasDK** [comment] 2021-01-07 09:26
Hi Peter.
Well , the uninstall of the agent fails with the error I posted , if I do not edit the agent config file and replace the certificate.
I can not replicate this now as I have upgraded the certificate on both my Sandbox and Prod environments , but the error was there up until I changed the agent config and replaced the certificate thumbprint.

**Comment by PeterRFriis** [comment] 2021-01-07 12:07
Hi George.
Yep. I understand but do you recall if you used the secondary thumbprint option in the cert upgrade of service fabric? or only overwrote the primary thumbprint, which is what I believe could be the reason for your situation.

If you do not recall, I would not recommend you to try and reproduce with your sandbox or prod, as I know certificate rotation, can be problematic and should only be done when needed.

Thank you,
Peter

**Comment by GeorgeSasDK** [comment] 2021-01-07 13:33
I have followed the procedure , added second ssl and made the old one as secondary , so I did not just replaced the thumbprint of the current certificate.

Part of my Json .

"CertificateInformation":  {
                                                                       "ClusterCertificate":  {
                                                                                                  "X509StoreName":  "My",
                                                                                                  "Thumbprint":  "649737147FA9A83A27734293F53694945873....",
												  "ThumbprintSecondary":  "770D45272A9B2D5285917C1CD6787DBD983....."
                                                                                              },
                                                                       "ServerCertificate":  {
                                                                                                  "X509StoreName":  "My",
                                                                                                 "Thumbprint":  "649737147FA9A83A27734293F5369494587.....",
												"ThumbprintSecondary":  "770D45272A9B2D5285917C1CD6787DBD98....."
                                                                                             },
                                                                       "ClientCertificateThumbprints":  [
                                                                                                            {
                                                                                                                "CertificateThumbprint":  "9D457B28544821EA96D123FADE5212AA89.....",
                                                                                                                "IsAdmin":  true
                                                                                                            }

So not sure why the error came.

I will not rotate the certificate again just to test , in 2 years when my certificate must be changed again , I will be able to come with some more feedback.

**Comment by PeterRFriis** [comment] 2021-01-07 13:54
Hi George
Great with the input! Thanks. Ill take this on to the team internally and we will see if we can reproduce and update the docs accordingly as needed.
Thanks for the help and the input!
Peter

**Comment by PeterRFriis** [comment] 2021-01-08 10:24
Hi @GeorgeSasDK 
We have investigated internally based on your feedback and the details you have provided, and it has been confirmed that there is a problem in the process. We have corrected the documentation internally and it should be publicized over the next couple of days.

Thank you very much for raising this to our attention! 
I wish you a great weekend.

@RobinARH the fix for this issue is being tracked by Pullrequest #10075, however I cannot link the 2 in the GitHub as one is public and the other internal. Please close this bug as fixed.

Thank you!
Peter

**Comment by faix** [comment] 2021-01-08 19:12
@RobinARH please feel free to close this. The related PR has been merged. Thanks!

**Closed** 2021-01-08 19:41 UTC
Labels: assigned-to-author, doc-bug, triaged-robin
