### ISSUE TITLE
The deep dive URL logic doesn't work in batch mode

### ISSUE THREAD

**Issue by FrozyDev** [MicrosoftDocs/dynamics-365-unified-operations-public#4097] opened 2022-07-27 17:13 UTC
The provided code on the page works create when a user session is active. When this code is run in batch, we need to replace the line using UrlUtility::GetURL() with some other code that doesn't rely on a user session:

The bellow code: 

   // gets the generator instance
    var generator     = new Microsoft.Dynamics.AX.Framework.Utilities.UrlHelper.UrlGenerator();
    /*
    // Works only with user session
    var currentHost   = new System.Uri(UrlUtility::getUrl());
    */

   // Alternative for Batch mode :
    IApplicationEnvironment env = EnvironmentFactory::GetApplicationEnvironment();
    str currentUrl = env.Infrastructure.HostUrl;
    System.Uri currentHost = new System.Uri(currentUrl);

    generator.HostUrl = currentHost.GetLeftPart(System.UriPartial::Authority);

Source : https://devblog.sertanyaman.com/2021/04/30/x-how-to-get-the-d365fo-url-correctly-inside-backend-services/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d72abb-aac1-5614-35e9-7f2ce87d3306
* Version Independent ID: 9523e31d-c663-179e-ac28-f11a9d21b6b3
* Content: [Create shareable, secured URLs (deep links) - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/user-interface/create-deep-links)
* Content Source: [articles/fin-ops-core/dev-itpro/user-interface/create-deep-links.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/user-interface/create-deep-links.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RobinARH
* Microsoft Alias: **sericks**

**Comment by josaw1** [comment] 2022-07-28 15:44
Thanks for the feedback. @jasongre can you please take a look?

**Comment by KendalBond007** [comment] 2023-07-31 18:22
Issue open since before doc publication 11 Aug 22 (> year). PVs consistent over the last two quarters (see image) suggesting matter is resolved. Scheduling item to be closed.

<img width="701" alt="image" src="https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/assets/104027141/f732890f-2815-421b-8716-a87089f58e03">


@josaw1 - I am unable to close the item; we can look into permissions as seems necessary. I will create a list to batch additional issues, and send the list to you to close issues. Hopefully that helps avoid a deluge of emails for you.

**Comment by johnmichalak** [comment] 2024-02-14 16:14
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:14 UTC
Labels: assigned-to-author, doc-bug, triaged-Jo
