### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by RuthGunn** [MicrosoftDocs/dynamics-365-unified-operations-public#2741] opened 2020-09-08 14:19 UTC
Within the article is this statement **_"Column header filters – When you filter a grid by using column header filters, you can change the filter operator as you require to find the data that you want. For example, you can change the operator from begins with to is exactly. Every time that you use a column header filter and change the filter operator, the app stores the change. Then, the next time that you filter on that column, the filter operator will be restored."_**

This statement is incorrect.  It doesn't work for all grids.  For instance, when you filter on the Sales Order Line Grid, the last filter used will not be saved for your next use.  In fact, this grid doesn't act like other grids and this big fact should be mentioned in the article along with any other grid it doesn't work for. 

In order to expedite manual Sales Order entry, MSFT developers should consider changing the filtering functionality to the Sales Order Line Grid.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8be7cd-8a59-b385-2c6a-763ebd5956fa
* Version Independent ID: 7f1dde5c-a26c-55bf-118c-513b95fe07e8
* Content: [Personalize the user experience - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/personalize-user-experience)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/personalize-user-experience.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/fin-ops/get-started/personalize-user-experience.md)
* Service: **dynamics-ax-applications**
* Product: ****
* Technology: ****
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by sericks007** [comment] 2020-09-09 11:45
@RuthGunn, thanks for providing this feedback.

@jasongre, please review and update the content, as necessary.

**Comment by sericks007** [comment] 2020-09-17 13:05
Bug 507311 has been logged to track this issue.

**Comment by jasongre** [comment] 2020-09-21 22:22
@RuthGunn just wanted to get some clarifications as I wasn't able to reproduce the issue you are pointing out. For reference, I tried on both on the Open sales order lines page, as well as lines grid after drilling into an order from the All sales order page. The value of the filter is not expected to save, but the filter operator (e.g. "is one of", "contains") was being remembered for me. Perhaps I'm looking at the wrong page or grid?

**Comment by RuthGunn** [comment] 2020-09-22 12:17
Hi Jason

I don’t believe you’re in an open sales order and trying to filter on the multiple lines.  I’d be happy to walk thru this will you and talk with you directly; however I don’t want to post my email or cell phone on GitHub.  If you can contact me directly, EST, I think that would be best.

Ruth Gunn

**Comment by jasongre** [comment] 2020-09-24 18:20
Hey @RuthGunn, feel free to email me at jasongre@microsoft.com

**Comment by sericks007** [comment] 2020-09-24 18:27
Hi @RuthGunn - I'm going to close this issue because @jasongre can't reproduce it.  If you walk Jason through the scenario, this can certainly be re-opened.  Thanks!

**Closed by sericks007** 2020-09-24 18:27 UTC
Labels: assigned-to-author, bug-created-VSTS, doc-bug, triaged-Sally
