### ISSUE TITLE
Please update the limitation section

### ISSUE THREAD

**Issue by swidz** [MicrosoftDocs/dynamics-365-unified-operations-public#2451] opened 2020-05-29 08:11 UTC
[Enter feedback here]

1. The limit for records maintained per table was increased to 2mln

2. It should be clearly explained that there are scenarios where referential integrity can be damaged:
a. Enable Customer Group sharing across all entities, with USMF being your main entity.
b. In USMF create customer group A. It will be replicated to other entities.
c. In GBSI create a customer and place it into customer group A. Everything is fine.
d. Back in USMF, delete customer group A. 
e. You end up with a customer in GBSI with and unexisting customer group Id
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07ba5d8f-e335-9d6f-0418-7529f19d558f
* Version Independent ID: 1ff0ba1d-54f0-8f59-49d3-c8ab44470cd9
* Content: [Cross-company data sharing - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/sysadmin/cross-company-data-sharing)
* Content Source: [articles/fin-ops-core/dev-itpro/sysadmin/cross-company-data-sharing.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/fin-ops-core/dev-itpro/sysadmin/cross-company-data-sharing.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @aprilolson
* Microsoft Alias: **aolson**

**Comment by kfend** [comment] 2020-05-29 21:19
@swidz - thanks for the feedback.
@aprilolson - please review and address this feedback as necessary.

**Comment by aprilolson** [comment] 2020-05-29 22:29
+@Par Akerblom<mailto:Par.Akerblom@microsoft.com> as I believe he now owns Record Sharing.

April Olson
Dynamics 365 Finance
Principal Group Product Manager
Check out our Financials blog: https://community.dynamics.com/365/financeandoperations/b/financials

Our workplace allows for a flexible work schedule, which is an amazing benefit. I am sending this now because it is convenient for me. I do not expect you to read or respond until it’s convenient for you.

**Comment by Peakerbl** [comment] 2020-05-31 22:00
Issue number 1. We are in the process of updating the content and this will include the new limits.

Issue number 2. This is a bug and we are working to fix this. This is not expected behavior.

**Comment by kfend** [comment] 2020-06-05 19:14
Closing as this has been addressed by the PM.

**Closed by kfend** 2020-06-05 19:14 UTC
Labels: assigned-to-author, triaged-kristin
