### ISSUE TITLE
Production control parameters

### ISSUE THREAD

**Issue by ClaesLaine** [MicrosoftDocs/dynamics-365-unified-operations-public#4273] opened 2022-11-10 09:33 UTC
There is no link to any page that describes the production control parameters
For AX2012 this existed https://learn.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/set-up-production-control-parameters
But there is no similar page for F&O.
But I am still missing an explanation of the parameter on standard update tab "Alert users when using non-standard formula version"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90a70666-74c8-cb14-f655-2ea665bd8b65
* Version Independent ID: 499e83f4-52c2-0292-b3d1-92dc69e957e3
* Content: [Production setup requirements - Supply Chain Management | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/production-set-up-requirements)
* Content Source: [articles/supply-chain/production-control/production-set-up-requirements.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/production-set-up-requirements.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by bishalgoswami** [comment] 2022-11-16 03:48
Bug 768914 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:36
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:36 UTC
Labels: bug-created-VSTS
