### ISSUE TITLE
Quarantine orders no longer supported for warehouse management processes (Quarantine orders page)

### ISSUE THREAD

**Issue by mmrauta** [MicrosoftDocs/dynamics-365-unified-operations-public#4108] opened 2022-08-05 14:15 UTC
Since version 10.0.25, as part of the bug fix, the quarantine orders have been disabled for warehouse management processes.
In this article there is a note that they are supported for return order which is not true anymore.
Could you please update the note?

Please notice there is a similar problem with another docs. I have created also this issue: 
[#4109](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/4109)

If you need more information, please contact me (Microsoft alias: mprazanowska)
Best regards,
Marta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d15d91e-dfde-2b47-f4c3-39fcaa31f35f
* Version Independent ID: 411c36f6-386d-07f6-3c55-bc737544df81
* Content: [Quarantine orders - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/inventory/quarantine-orders)
* Content Source: [articles/supply-chain/inventory/quarantine-orders.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/inventory/quarantine-orders.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @yufeihuang
* Microsoft Alias: **yufeihuang**

**Comment by johnmichalak** [comment] 2022-08-05 15:32
@mmrauta Thank you for the feedback.

@yufei-huang Please take a look at the suggestion and update the article as appropriate.

**Comment by KendalBond007** [comment] 2023-10-05 20:20
@yufei-huang - Following up: any additional work needed on this, or can we slate it to close?

@josaw1
@johnmichalak

**Comment by johnmichalak** [comment] 2024-02-14 16:19
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:19 UTC
Labels: assigned-to-author, triaged-john
