### ISSUE TITLE
F365 FO Localization - International Availability Guide

### ISSUE THREAD

**Issue by craigfraser9** [MicrosoftDocs/dynamics-365-unified-operations-public#1211] opened 2019-04-29 12:55 UTC
Can anyone advise the implications for Countries which do not feature in the Availability section. I have a requirement to set up a Legal Entity for Cambodia however it does not feature in the "Availability" section of the International Availability guide. Can D365 FO still be deployed in Cambodia and if so what does the lack of mention in the "Availability" section imply?

**Comment by RobinARH** [comment] 2019-04-29 18:40
Duplicate of https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/1212.

**Closed by RobinARH** 2019-04-29 18:40 UTC
Labels: duplicate, triaged
