### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by xDynaMike** [MicrosoftDocs/dynamics-365-unified-operations-public#4256] opened 2022-11-03 08:31 UTC
Hi,

We should have documentation for Data Expansion Tool V2 which by default is not enabled. There is a flight called "EnableDataExpansionTool".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1016eba2-a0f9-8890-beb4-7c9f9f6df4fc
* Version Independent ID: 57758813-9d36-975a-eb6f-551b7da3e276
* Content: [Data management overview - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages#features-flighted-in-data-management-and-enabling-flighted-features)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-entities-data-packages.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment] 2022-11-03 10:31
Bug 762941 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:31
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:31 UTC
Labels: bug-created-VSTS
