### ISSUE TITLE
Data Entity loading order is not fully covered by data templates

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/dynamics-365-unified-operations-public#1557] opened 2019-08-02 21:25 UTC
Using data templates to find the correct loading order is time consuming AND it does not cover all the data entities, e.g. Customer postal addresses, Positions, Customer invoice journal header, Customer invoice journal line, Purchase requisitions, Purchase requisition lines, etc. I cannot find a single master data entity reference document from Microsoft that provides this needed data loading order information. Inexcusable!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b96d110-3328-c362-6b0e-695864e30c5d
* Version Independent ID: 7fe04722-103b-2f60-a891-ed1b5e8c1f3f
* Content: [Find information about standard data entities - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-entities-report?toc=/fin-and-ops/toc.json)
* Content Source: [articles/dev-itpro/data-entities/data-entities-report.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/data-entities/data-entities-report.md)
* Service: **dynamics-ax-platform**
* Product: ****
* Technology: ****
* GitHub Login: @MargoC
* Microsoft Alias: **margoc**

**Comment by josaw1** [comment] 2019-08-09 21:07
Bug 349653 created to track this issue.

**Comment by ronsonntag54** [comment] 2020-05-26 18:51
So nothing has been done to respond to my issue in 9 months?

**Comment by ronsonntag54** [comment] 2021-05-25 15:54
Not impressed. Going on 1.5 years with no follow-up. I have seen numerous comments all over the web of consultants having problems with Data Entity loading order. Apparently Microsoft does not consider this issue important.

**Comment by RobinARH** [comment] 2021-11-06 00:21
Closing this as a duplicate of https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/3369.

**Closed by RobinARH** 2021-11-06 00:21 UTC
Labels: assigned-to-author, bug-created-VSTS, triaged-kristin
