### ISSUE TITLE
Cannot add child entities to the BYOD export Projects

### ISSUE THREAD

**Issue by latifdindoruk** [MicrosoftDocs/dynamics-365-unified-operations-public#3037] opened 2020-12-18 08:13 UTC
Hello Dear All,

According to the text, the writer says that "Composite entities cannot be added to the BYOD export projects. If you need you should export child entities" in a purple bubble. However, when I try to do that, child entities cannot be shown in the BYOD export project lines. After all, when I want to add that again system says, the project already has that entity. 
Could you please help,

Thanks,
Latif

**Comment by kfend** [comment] 2020-12-18 20:34
Hi @latifdindoruk, thank you for the feedback. Can you tell me specifically what topic you are referring to? Thank you!

**Comment by kfend** [comment] 2020-12-18 20:36
Looks like this is a duplicate of [another issue](https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/3038). I am going to close this one and we will work from the other. Thanks!

**Closed by kfend** 2020-12-18 20:36 UTC
Labels: needs-more-info, triaged-kristin
