### ISSUE TITLE
The command for mass deployment of hardware station is outdated 

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/dynamics-365-unified-operations-public#4259] opened 2022-11-03 12:20 UTC
The mass deployment script for Sealed Hardware station is shown in the [article](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/enhanced-mass-deployment#silently-install-hardware-station) is incorrect. 

The sample script should be as below 
.\CommerceHardwareStationSetup install --Port 8443 --csuurl "https://scuxxxxxxxx-rs.su.retail.dynamics.com/Commerce" --hostname XXXXXX --certthumbprint "9f8fa141xxxxxxxxxxxxxxxxxxxxxxxxx"

The description for some of the delimiters used are not available in the below [table](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/enhanced-mass-deployment#delimiters-for-mass-deployment). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c22f987b-3d20-554d-467a-cdcdf404b0bd
* Version Independent ID: 0160ae8d-09c7-d54c-83bf-10fbec9842e9
* Content: [Mass deployment of sealed Commerce self-service components - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/enhanced-mass-deployment)
* Content Source: [articles/commerce/dev-itpro/Enhanced-Mass-Deployment.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/Enhanced-Mass-Deployment.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @jashanno
* Microsoft Alias: **jashanno**

**Comment by bishalgoswami** [comment] 2022-11-03 12:31
Bug 762951 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:31
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:31 UTC
Labels: bug-created-VSTS
