### ISSUE TITLE
Date seems wrong

### ISSUE THREAD

**Issue by MarcRohde** [MicrosoftDocs/dynamics-365-unified-operations-public#4121] opened 2022-08-12 21:49 UTC
I the first paragraph of the page it states "To avoid last-minutes issues when deprecation is enforced, we strongly encourage you to complete the migration before December 1, 2020"

That was almost two years ago -- is there a new planned deprecation for traditional planning? If not this seems a little extreme since i it still isn't mandatory.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36c4831-276b-03c6-6f92-532746789338
* Version Independent ID: 5fdd62c5-5a0a-bf23-6dab-ad3717f5f70d
* Content: [Get started with Planning Optimization - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/get-started)
* Content Source: [articles/supply-chain/master-planning/planning-optimization/get-started.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/master-planning/planning-optimization/get-started.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @t-benebo
* Microsoft Alias: **benebotg**

**Comment by kfend** [comment] 2022-08-15 17:56
@MarcRohde - Thank you for the question.
@t-benebo - Can you please take a look and update the article as needed? Thanks!

**Comment by johnmichalak** [comment] 2024-02-14 16:22
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by johnmichalak** 2024-02-14 16:22 UTC
Labels: assigned-to-author, doc-bug, triaged-kristin
