### ISSUE TITLE
Where is the tokens being removed ? Headquarters? or store database?

### ISSUE THREAD

**Issue by cscott00** [MicrosoftDocs/dynamics-365-unified-operations-public#4614] opened 2023-06-27 15:57 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdf4ab02-7594-51e3-22c7-5bcc0903c879
* Version Independent ID: bdf4ab02-7594-51e3-22c7-5bcc0903c879
* Content: [Limit payment token usage - Commerce | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/limit-token-usage)
* Content Source: [articles/commerce/dev-itpro/limit-token-usage.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/limit-token-usage.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @BrianShook
* Microsoft Alias: **brshoo**

**Comment by bishalgoswami** [comment] 2023-08-10 11:32
Bug 834388 has been logged to address this issue.

**Comment by twheeloc** [comment] 2024-02-14 18:38
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by twheeloc** 2024-02-14 18:38 UTC
Labels: bug-created-VSTS
