### ISSUE TITLE
Binary ISVs are not pulled into the package correctly

### ISSUE THREAD

**Issue by inovsn** [MicrosoftDocs/dynamics-365-unified-operations-public#3275] opened 2021-04-08 13:14 UTC
[Enter feedback here]
There is a conversation in Yammer that describes an additional step required to copy in directories other than just the BIN directory from ISVs that don't provide source and are not compiled.  The "official" version of how to do this should be added to this page so that those of us that know we have binary only ISVs don't just "discover" this issue and have to go searching Yammer for a resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10459944-bcf8-c5fa-d180-9fb4bb3722da
* Version Independent ID: 29ae9d16-ed7c-92d8-0300-4fc46c777ddf
* Content: [Build automation that uses Microsoft-hosted agents and Azure Pipelines - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/hosted-build-automation.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by tonyafehr** [comment] 2021-04-08 13:31
@jorisdg, please review and consider making updates.

**Comment by jorisdg** [comment] 2021-04-08 17:29
I've sent a pull request to elaborate. The pipeline doc will explicitly call out reviewing the packaging step. The packaging step doc is being updated with more information as well as examples (including calling out ISVs specifically). And the "including third party packages" doc is updated to mention and link to the packages doc as well.

The Yammer threads are not correct either. The COPY step was never meant to include ISVs, which is why they are incomplete. It was intended to solve the case where you have DLLs checked into your bin folder that are required to compile your X++ code.

Instead, the packaging step should be instructed to include the specific binary packages you need from the source folder. For example, use the following in your packaging step to include all X++ modules you're compiling, excluding any modules whos names end in "Tests", and including two ISV modules that are in your source repository:

*
!*Tests
$(Build.SourcesDirectory)\Metadata\MyISV1
$(Build.SourcesDirectory)\Metadata\MyISV2

**Closed** 2021-04-08 22:35 UTC
Labels: assigned-to-author, doc-enhancement, triaged-Tonya
