### ISSUE TITLE
Configuration repository type File System does not exist

### ISSUE THREAD

**Issue by AnandGoel813** [MicrosoftDocs/dynamics-365-unified-operations-public#4290] opened 2022-11-20 07:37 UTC
Hi Team,
I am testing the functionality and came upon an issue while creating the configuration repository. We have 3 values available on the form which are mentioned below-
1. LCS
2. Operations resources
3. RCS

But I couldn't find the type 'File system' as mentioned on the doc page. Request you to please look into the same and either correct the type on the doc page or guide me to take extra steps to find the required type.

Thank you and Regards,
Anand

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de0a2084-5f5c-ed42-e8bd-1a07fa3de68a
* Version Independent ID: eff56ef3-f1c1-67d3-e44e-dea23214ee12
* Content: [Import Electronic reporting (ER) configurations - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/electronic-reporting-import-ger-configurations)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/electronic-reporting-import-ger-configurations.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/electronic-reporting-import-ger-configurations.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **filatovm**

**Comment by bishalgoswami** [comment] 2022-11-20 08:02
Bug 770012 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 18:45
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 18:45 UTC
Labels: bug-created-VSTS
