### ISSUE TITLE
When will the recalculate button will be removed?

### ISSUE THREAD

**Issue by StephenMakar** [MicrosoftDocs/dynamics-365-unified-operations-public#4124] opened 2022-08-16 22:50 UTC
First note in page states: 
" Note

After a coupon is linked to a discount, several fields on the discount page in Commerce become read-only, because they are managed by the coupon's settings. These fields include the fields for the status and standard date ranges.

While using the coupon in the call center channel, you need to select the Recalculate button (Sell tab > Calculate > Recalculate) in order for the discount associated to the coupon to get applied. This additional step will be removed in a future release."

It sounds like the Recalculate button will be removed in the future. 

Do we know when this will be?

Thanks,
Stephen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731c7f9e-32cb-958e-23e2-88e834c1dd63
* Version Independent ID: 8b2d21fc-9a0d-d0b4-55bd-f0b0b99baf46
* Content: [Set up coupons for retail sales - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/retail-coupons)
* Content Source: [articles/commerce/retail-coupons.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/retail-coupons.md)
* Service: **dynamics-365-commerce**
* Product: ****
* Technology: ****
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by twheeloc** [comment] 2022-08-17 17:52
@StephenMakar, thank you for the feedback.
@josaw1, will you please assign this to the correct PM to address? Thanks!

**Comment by bishalgoswami** [comment] 2022-08-22 13:13
Bug 734204 has been logged to address this issue.

**Comment by josaw1** [comment] 2022-08-22 16:26
@boycez can you please review this comment?

**Comment by johnmichalak** [comment] 2024-02-14 16:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by johnmichalak** 2024-02-14 16:23 UTC
Labels: assigned-to-author, doc-enhancement, bug-created-VSTS, triaged - tammy
