### ISSUE TITLE
Content Issue

### ISSUE THREAD

**Issue by Prasanthtvpm** [MicrosoftDocs/dynamics-365-unified-operations-public#4129] opened 2022-08-22 13:28 UTC
[This page seems to have wrong content and image. Figure 2 seems to be wrong, as it does not show part E which is there in Figure 1. Moreover in Figure 2, ABC are shown as packaging items. If C is a packaging item, it should ideally be in sequence 30]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8edfe78b-6486-5678-a171-95f81d2715ef
* Version Independent ID: 62a24546-bb3f-5194-43f0-0db144643ab7
* Content: [Phantom items - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/supply-chain/production-control/phantom-items#feedback)
* Content Source: [articles/supply-chain/production-control/phantom-items.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/supply-chain/production-control/phantom-items.md)
* Service: **dynamics-365-supply-chain**
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by bishalgoswami** [comment] 2022-08-22 13:31
Bug 734216 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:25
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:25 UTC
Labels: bug-created-VSTS
