### ISSUE TITLE
How do I connect to this data from PowerBI side?

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/dynamics-365-unified-operations-public#335] opened 2018-08-29 08:52 UTC
This is not covered in the documentation, at least a link to applicable documentation would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a076-d364-f4e8-fe37-f10c77a75466
* Version Independent ID: 0f767e21-3f33-2139-0931-7cd044c81b9f
* Content: [Power BI integration with Entity store - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/analytics/power-bi-integration-entity-store)
* Content Source: [articles/dev-itpro/analytics/power-bi-integration-entity-store.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/analytics/power-bi-integration-entity-store.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @MilindaV2
* Microsoft Alias: **milindav**

**Comment by sericks007** [comment] 2018-08-29 14:03
Thanks for letting us know about this issue. We'll investigate.

**Comment by sericks007** [comment] 2018-09-12 21:15
Bug 246533 has been logged to track this issue.

**Comment by kmescha** [comment] 2019-01-05 16:40
Any updates on this bug 246533?

**Comment by jwilliams-bhsolutions** [comment] 2019-01-10 00:03
@kmescha I know these aren't full details, but to get you started: connecting to Entity Store data can be done in PowerBI desktop in non-production environments by installing PBI Desktop application in the Windows server of the environment, and connecting to the local SQL DB (or Azure SQL DB for Tier 2 boxes) the way you would expect.  After you model the report, you need to publish the PBI Desktop file for use in PBI Embedded (this GitHub issue has some information on how to do that: https://github.com/MicrosoftDocs/dynamics-365-unified-operations-public/issues/620).  Unfortunately, you can't connect directly to the Entity Store in production (you can only deploy PBI Embedded files through X++ to do so).

**Comment by HenrikBo** [comment] 2019-01-18 13:40
@jwilliams-bhsolutions are there any changes to this with the upcoming release of version 10?..

**Comment by kmescha** [comment] 2019-01-18 15:35
jwilliams, thanks I was able to figure that part out and I'm able to connect and create models on the database directly with direct query in Power BI. The problem is that we want to enable Business Users to model the data and build reports and having them log into a server to do so is not a very good solution. They need to build reports on Production data as they don't understand the concepts of dev/test etc. I'm not sure this is a great end user experience the way this is currently implemented.

**Comment by jwilliams-bhsolutions** [comment] 2019-01-18 15:55
@kmescha no disagreement here - the experience isn't fantastic.  My two cents, I would consider using BYOD feature to extract your data to another Azure SQL environment and report off there.  You might also optionally consider building a Data Warehouse and modelling that data.  I know there's more cost there and more infrastructure.

The only other thing to think about is using the Open in Excel experience to get data to an Excel doc and then build the PBI directly off the Excel doc.  Then you can refresh the Excel spreadsheet (since it has a live connection) and correspondingly refresh the PBI import.  Not a great option but it does give a little bit more of a true "democractic data access" experience.

**Comment by jwilliams-bhsolutions** [comment] 2019-01-18 15:56
@HenrikBo I don't have any reason to believe this is going to change with 10.0 since that is primarily about a continuous update experience.  That said - there may be specific features that affect this that I'm not familiar with.

**Comment by SST1982** [comment] 2019-01-23 08:23
Hi all, seems the envisioned solution to access Entities of Entity Store by MSFT is using Azure Data Lake from Version 10 onwards. Quote from Release notes April '19: 

> Transactional and master data in the Entity store will be published to customer’s Data Lake.
Microsoft will keep the data fresh on a real-time basis.

**Comment by jwilliams-bhsolutions** [comment] 2019-01-24 00:32
Thanks @SST1982 for sharing!  This is great info (read more at: https://docs.microsoft.com/en-us/business-applications-release-notes/april19/dynamics365-finance-operations/erp-data-entity-store-byod-business-data-lake).  In the interest of discussion this is basically another flavor of BYOD with a target of the Data Lake instead of an Azure SQL database (obvious benefits here).  

BYOD II was always meant to allow us to publish the star schema aggregate measures from Entity Store to other locations (allowing the flow of optimized reporting data structures out of F&O).  The most exciting piece in my mind is the incremental change tracking into the Data Lake.  However, this is obviously difficult with a star-schema model so I'll be interested in how this will be implemented (or when).  

A few limitations I see though - keep in mind though that the documentation doesn't detail that PowerBI Embedded in D365 will support consumption from a BYODLake - just that you can use PowerBI Service on top of it (bring your own Pro license to share or consume shared dashboards).

It's also important to note that the BYODL, while a better storage solution due to HDFS style compression, is not inherently modelled data (combat this by pre-defining aggregate measures of course, but you will limit your ability to consume other application data such as a payment system and will be subject to the potential change tracking complications for modelled data I mentioned above). 
 Finally, consider that "transactional and master data" is limited to the extant data entities in D365 (many customers might be interested in inventory transaction data, for example, especially if they can store a lot of it for cheap - but would have to build their own custom entity to do so, not a difficult task but a customization in X++ that is required)

**Comment by sericks007** [comment] 2020-03-27 14:00
Closing this issue as there haven't been any comments in over a year.

**Closed by sericks007** 2020-03-27 14:00 UTC
Labels: assigned-to-author, bug-created-VSTS, doc-bug, triaged
