### ISSUE TITLE
Mentioned version numbers

### ISSUE THREAD

**Issue by JeroenLeeflang** [MicrosoftDocs/dynamics-365-unified-operations-public#4286] opened 2022-11-18 14:52 UTC
On this page, version number for quality updates are provided. 

Are this examples? That should be made more clear.

In LCS, the quality update has a higher number already.

![image](https://user-images.githubusercontent.com/17065880/202732392-727558f5-4c21-435f-a05e-a7e5d81ce422.png)

Or will this page be updated every time a new version of the quality update 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates?context=%2Fdynamics365%2Fcontext%2Ffinance)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by johnmichalak** [comment] 2024-02-14 17:45
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:45 UTC
Labels: bug-created-VSTS
