### ISSUE TITLE
Unable to "Reprovision the target environment"

### ISSUE THREAD

**Issue by firyanis** [MicrosoftDocs/dynamics-365-unified-operations-public#943] opened 2019-02-20 10:43 UTC
In this scenario, it is not possible to reprovision. A build environment is not allowing to apply the "Environnement reprovioning tool" package through LCS.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: dbfc55db-29cd-7e02-772a-4e590ff1fa78
* Version Independent ID: e4594af2-7087-6795-43f8-86cb3349534f
* Content: [Debugging and diagnostics - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/fr-fr/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-debugdiag)
* Content Source: [articles/dev-itpro/database/dbmovement-scenario-debugdiag.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/dbmovement-scenario-debugdiag.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laneswenka**

**Comment by sericks007** [comment] 2019-02-20 15:09
@firyanis, thanks for posting this!

@laneswenka, can you please review and update the content, as necessary.

**Comment by laneswenka** [comment] 2019-02-20 18:24
Hi @firyanis I am able to import the package to the asset library in a given LCS project, and thereafter I see it as a valid option to apply against a build server.  Can you explain in more detail what issue you experience?

**Comment by firyanis** [comment] 2019-02-22 10:59
Hello @sericks007 and @laneswenka 

For every LCS project where we deployed a "Build" environment in the "Sandbox: Developer and test" slot, when I go to "Maintain" -> "Apply updates", i can't find the "Environment reprovisioning tool" in the list. I confirm that before doing that, i imported the deployable package in the asset library of the LCS project from the shared asset library.

If you wish, we can do a screen sharing session and i will show you.

Regards.

**Comment by firyanis** [comment] 2019-02-26 08:40
Hello @sericks007 and @laneswenka

Any update on this ? :)

**Comment by sericks007** [comment] 2019-02-26 13:45
@laneswenka, can you please review and update the content, as necessary.  Thanks!

**Comment by sericks007** [comment] 2019-02-27 17:23
Bug 296962 has been logged to track this issue.

**Comment by RakeshDataAnalytics** [comment] 2019-07-05 09:26
Hi Am getting below error after following above steps, please suggest.


Exception information: 
    Exception type: HttpCompileException 
    Exception message: k:\AosService\WebRoot\App_Code\LocalizationController.cs(89): error CS0103: The name 'WebClientEventSource' does not exist in the current context
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()


There is a problem with the server

Sorry, the server has encountered an error. It is either not available or it can't respond at this time. Please contact your system administrator.

ERROR 500.

I am able to connect to UAT DB in DEV server.

Please suggest!

RAKESH DAMASANI



Exception information: 
    Exception type: HttpCompileException 
    Exception message: k:\AosService\WebRoot\App_Code\LocalizationController.cs(89): error CS0103: The name 'WebClientEventSource' does not exist in the current context
   at System.Web.Compilation.AssemblyBuilder.Compile()

**Comment by laneswenka** [comment] 2019-07-31 22:48
Hi @RakeshDataAnalytics that doesn't sound like a typical error and you'll want to create a support ticket.  @firyanis I will create a Build topology in the Sandbox Develop and Test slot as compared to a Cloud-hosted Build server to see if that is the difference.

**Comment by laneswenka** [comment] 2019-08-15 16:18
It appears this is by design for build servers.  If you need retail to be functioning you'll have to use either a Sandbox UAT or a Sandbox DevTest environment type.  @sericks007 this can be closed as by design.  The https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/dbmovement-scenario-exportuat article also calls out that this is for developer environments.

**Closed** 2019-08-16 13:02 UTC
Labels: assigned-to-author, bug-created-VSTS, doc-bug, triaged
