### ISSUE TITLE
Is there any docs for Backorder Purchase Lines in Dynamics 365

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/dynamics-365-unified-operations-public#4323] opened 2022-12-14 09:32 UTC
I couldn't find any docs regarding **Backorder Purchase Lines**.  (Procurement & Sourcing > All Vendors > Procurement (Action Pane) > Purchase Order > Backorder Purchase Lines)

Is it same working same as **AX2012** which is mentioned in the following link?
[https://learn.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/about-backorders](url)

**Comment by johnmichalak** [comment] 2024-02-14 20:16
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:16 UTC
