### ISSUE TITLE
Self-service database export not available on all Sandbox environments in LCS

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#758] opened 2019-01-07 00:41 UTC
The Self-service database export is not available in our Sandbox environment. The option simply doesn't appear under the Maintain button. Therefore, I assume we still have to perform the older manual method of exporting the bacpac from the Command Prompt. However, the instructions for this are no longer available on this page. 
Can you either re-publish the old instructions, or explain how to enable Self-service database export in any Sandbox environment in LCS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3436fbc8-5bdd-dcdc-f5d3-51caf7b6cd76
* Version Independent ID: af78d3ef-b329-11e9-896a-aa3394f6c77c
* Content: [Copy Finance and Operations databases from Azure SQL Database to SQL Server environments - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/database/copy-database-from-azure-sql-to-sql-server)
* Content Source: [articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/database/copy-database-from-azure-sql-to-sql-server.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by ShylaThompson** [comment] 2019-01-07 17:53
@laneswenka can you review and comment?

**Comment by laneswenka** [comment] 2019-01-07 18:39
@dhand01 the option should be there, I have validated on 5 different environments in different projects, and we don't have other reports of this.  Can you ensure you are using the Maintain -> Move Databases -> Export database option?

**Comment by laneswenka** [comment] 2019-01-07 18:40
@dhand01 also can you confirm you are an Environment Manager or a Project Owner in LCS?

**Comment by dhand01** [comment] 2019-01-07 18:45
Yes. I'm a project owner:

[image: image.png]

**Comment by dhand01** [comment] 2019-01-07 18:46
I do not have the "Move databases" option under Maintain button.

[image: image.png]

**Comment by laneswenka** [comment] 2019-01-07 19:11
Hi @dhand01 can you email me your EnvironmentID from LCS and I can take a look!  lane.swenka[at]microsoft.com

**Comment by dhand01** [comment] 2019-01-07 19:12
d371bbc9-def9-4720-a142-cf7bd620ba0e

**Comment by sericks007** [comment] 2019-01-14 14:59
Bug 282873 has been logged to track this issue.

**Comment by dhand01** [comment] 2019-01-26 17:15
Its been 12 days. Any update? We still do not have the Move Database option in LCS, nor are the instructions updated. HELP!

**Comment by robabb123** [comment] 2019-01-28 03:18
There are a number of our customer projects which do not have this option either. Some do, some don't.
I needed to use the old method of restoring from bacpac recently.

**Comment by laneswenka** [comment] 2019-02-04 19:21
@dhand01 @robabb123 we are not able to reproduce this on our end, and haven't had other reports of this come in via support.  Can you create a support ticket and then email me the ticket number and I can  help diagnose.  

The Export functionality is not customer or user specific, it is available for any Sandbox Tier2+ environment (Acceptance Test) for the Environment Manager and Project Owner roles.

It's possible that if you participated in the private preview there is a conflicting beta key record in our system for your account but again would need to diagnose that via Support ticket.

**Comment by sericks007** [comment] 2019-02-04 19:36
Closing this issue, as a support ticket should be opened.

**Closed by sericks007** 2019-02-04 19:36 UTC
Labels: assigned-to-author, bug-created-VSTS, doc-enhancement, in-progress, product-question, triaged
