### ISSUE TITLE
Missing information about standard PL functionalities

### ISSUE THREAD

**Issue by mkowalka** [MicrosoftDocs/dynamics-365-unified-operations-public#4355] opened 2022-12-29 15:04 UTC
Hi, 

On the page we are missing: 
1. how to create a credit note with corrective lines for Sales orders/Free text invoice 
2. How to process advance invoices on Sales order / FTI 

Please add this instruction on some sub-page. 

BR, 
Monika

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69e93824-6780-0b06-d769-e4c853a26756
* Version Independent ID: 8e26cf6b-f4f6-4bd6-710e-4e11ad145231
* Content: [Poland overview - Finance | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/finance/localizations/poland)
* Content Source: [articles/finance/localizations/poland.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/finance/localizations/poland.md)
* Service: **dynamics-365-finance**
* Product: ****
* Technology: ****
* GitHub Login: @kfend
* Microsoft Alias: **kfend**

**Comment by johnmichalak** [comment] 2024-02-14 20:36
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:36 UTC
