### ISSUE TITLE
The documentation is not clear enough about the need of the default record in the service levels (spanish)

### ISSUE THREAD

**Issue by Ginn-Hernandez** [MicrosoftDocs/dynamics-365-unified-operations-public#4116] opened 2022-08-10 17:38 UTC
The documentation mentions the default record for the service levels, but is not clear enough about the need of this record to be an "empty level" so several customers create different services levels and then this can cause errors when used in the Asset management API within the Dynamics 365 app. 

There have been several cases that were solved by adding this line, and they could have being avoided if the documentation were more clear about it

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0a8431b8-3db0-2d8e-c54f-9ea503490d06
* Version Independent ID: 4ffb76cc-1696-f413-a327-6486560a7ded
* Content: [Niveles de servicio de activos - Supply Chain Management | Dynamics 365](https://docs.microsoft.com/es-es/dynamics365/supply-chain/asset-management/setup-for-objects/object-priorities)
* Content Source: [articles/supply-chain/asset-management/setup-for-objects/object-priorities.md](https://github.com/MicrosoftDocs/Dynamics-365-Operations.es-es/blob/live/articles/supply-chain/asset-management/setup-for-objects/object-priorities.md)
* Service: **dynamics-365-supply-chain**
* Product: ****
* Technology: ****
* GitHub Login: @johanhoffmann
* Microsoft Alias: **johanho**

**Comment by kfend** [comment] 2022-08-15 18:08
@Ginn-Hernandez - Thank you for the feedback. 
@johanhoffmann - Can you please review this issue and update the article as needed? Thanks!

**Comment by johnmichalak** [comment] 2024-02-14 16:21
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:21 UTC
Labels: assigned-to-author, doc-bug, triaged-kristin
