### ISSUE TITLE
The synchronize customers job name is incorrect

### ISSUE THREAD

**Issue by Weicheng-Gao** [MicrosoftDocs/dynamics-365-unified-operations-public#4105] opened 2022-08-02 15:12 UTC
> Run the **Synchronize customers and business partners from async mode** job to create customer account IDs. (This job was formerly named **Synchronize customers and business partners from async mode**.)

The former name is exactly same to the current name. Please double check it.
The history of this job name should be:
> Create customers from async mode
> Synchronize customers and business partners from async mode
> Synchronize customers and channel requests (latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b7e67b-6e19-0344-d2cb-f348a8b2c550
* Version Independent ID: 60b7e67b-6e19-0344-d2cb-f348a8b2c550
* Content: [Convert asynchronous customers to synchronous customers - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/convert-async-to-sync)
* Content Source: [articles/commerce/convert-async-to-sync.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/convert-async-to-sync.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @gvrmohanreddy
* Microsoft Alias: **gmohanv**

**Comment by johnmichalak** [comment] 2022-08-03 16:05
@Weicheng-Gao Thank you for the feedback.

@gvrmohanreddy Please review the suggestions and update the article as appropriate.

**Comment by KendalBond007** [comment] 2023-10-05 19:45
@gvrmohanreddy - Following up: any additional work needed on this, or can we slate it to close?

@josaw1
@johnmichalak

**Comment by Weicheng-Gao** [comment] 2023-10-09 02:24
Hi all,

Looks the content is not changed.
Convert asynchronous customers to synchronous customers - Commerce | Dynamics 365 | Microsoft Learn<https://learn.microsoft.com/en-us/dynamics365/commerce/convert-async-to-sync>
[cid:d951a4f8-c141-4f64-848e-27c1977dfe0b]

Weicheng
________________________________

**Comment by johnmichalak** [comment] 2024-02-14 16:16
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:16 UTC
Labels: assigned-to-author, documentation, triaged-john
