### ISSUE TITLE
Page 

### ISSUE THREAD

**Issue by yobryon** [MicrosoftDocs/dynamics-365-unified-operations-public#4135] opened 2022-08-23 20:44 UTC
This page still advises to use the CommerceControllerAsync, which has been deprecated since 10.0.19, where the deprecation notice advises using IController instead.

Can the documentation be updated to reflect this? And in addition, is there still a standard way for us (customers) to create Bound controllers (where IController seems to be primarily for making unbound controllers).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf6c31b7-96fc-fa60-71ed-16ddeb9a69df
* Version Independent ID: df2225a3-0210-29f9-f1ba-1e6c3cfea6ae
* Content: [Create asynchronous Commerce (CRT) APIs in your business logic - Commerce | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/async-commerce-extension)
* Content Source: [articles/commerce/dev-itpro/async-commerce-extension.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/commerce/dev-itpro/async-commerce-extension.md)
* Service: **dynamics-365-commerce**
* GitHub Login: @josaw1
* Microsoft Alias: **josaw**

**Comment by yobryon** [comment] 2022-08-23 20:56
Update - I did stumble across the page a few before this one (in the ToC) that does explain it. Consider my ask revised to :  can the docs be updated to remove the advice to use the obsolete API, and maybe have the section on this page refer instead to the _Create a Retail Server extension API_ page (https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-server-icontroller-extension)?

Thanks!

**Comment by bishalgoswami** [comment] 2022-08-23 21:33
Bug 734601 has been logged to address this issue.

**Comment by josaw1** [comment] 2022-08-23 23:23
@mugunthanm can you please review this feedback?

**Comment by johnmichalak** [comment] 2024-02-14 16:27
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:27 UTC
Labels: bug-created-VSTS
