### ISSUE TITLE
Its GxP not GPX

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/dynamics-365-unified-operations-public#4235] opened 2022-10-20 08:19 UTC
The references on this page are incorrect. GxP. Good Practice supported by FDA within industries like Pharma. Not sure what GPX is!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates#what-about-fda-regulation-and-gpx)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment] 2022-10-20 10:12
Bug 759364 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:22
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:22 UTC
Labels: bug-created-VSTS
