### ISSUE TITLE
D365 Sales setting required and will be good to add here in this document.

### ISSUE THREAD

**Issue by VP-Avanade** [MicrosoftDocs/dynamics-365-unified-operations-public#4333] opened 2022-12-16 03:02 UTC
[Enter feedback here]
Can you please also update the document to mention the following configuration in order to get price from D365 SCM pricing engine

Settings on D365 Sales App under Settings -> Administration -> System settings -> Sales tab where the field "Use system pricing calculations" should be set to "No" 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/120697869/208012306-2caacf0c-7b3d-4a93-9ea6-3edf1f7be370.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e731aa1b-9e87-167e-5743-e1347c4de71e
* Version Independent ID: 84086073-f7bf-bd74-4e2a-fe32fc36c7d0
* Content: [Sync on-demand with the Supply Chain Management pricing engine - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/dual-write/pricing-engine#use-the-pricing-engine-from-supply-chain-management-in-sales)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/dual-write/pricing-engine.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/dual-write/pricing-engine.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @RamaKrishnamoorthy
* Microsoft Alias: **ramasri**

**Comment by johnmichalak** [comment] 2024-02-14 20:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:23 UTC
Labels: bug-created-VSTS
