### ISSUE TITLE
End of life

### ISSUE THREAD

**Issue by SAGDAVIDAD** [MicrosoftDocs/dynamics-365-unified-operations-public#1462] opened 2019-07-05 13:50 UTC
Hello Team,
In this article you mentioned "Microsoft will support the Dynamics 365 for Finance and Operations (on-premises) software through December 31, 2027" it means that after this date Microsoft will no longer provide D365FO on-premise and customers will have to switch to the cloud solution?
Thank you and best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72cf04b4-6ca4-218f-7a24-2945a11181ab
* Version Independent ID: f98f2ccc-caa8-de10-b64d-7398786e481b
* Content: [Software lifecycle policy and on-premises releases - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/migration-upgrade/on-prem-version-update-policy#feedback)
* Content Source: [articles/dev-itpro/migration-upgrade/on-prem-version-update-policy.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/migration-upgrade/on-prem-version-update-policy.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @meeramahabala
* Microsoft Alias: **meeram**

**Comment by kfend** [comment] 2019-07-12 16:36
@sarvanisathish - Sarvani, can you address this question? Thanks!

**Comment by SAGDAVIDAD** [comment] 2019-07-16 07:01
Any news?

**Comment by tonyafehr** [comment] 2019-07-19 14:45
Bug 342559 has been logged to track this issue.

**Comment by andrew1234560** [comment] 2023-08-16 19:11
Dear all, I am new here. I was wondering if there is any new information about the end date of D365 Finance & Operations on premise? The end date of December 2027 is still on Microsoft Learn, but I think this should be updated....? 
People take this for truth and if it is not correct, then people will make wrong decisions. Thanks! Regards, Andrew

**Comment by josaw1** [comment] 2023-08-17 18:51
@laneswenka can you please help with this issue?

**Comment by johnmichalak** [comment] 2024-02-14 16:12
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:12 UTC
Labels: assigned-to-author, product-question, bug-created-VSTS, triaged-kristin
