### ISSUE TITLE
FAQ - What about pending custom deployable packages?

### ISSUE THREAD

**Issue by woutermijle** [MicrosoftDocs/dynamics-365-unified-operations-public#4219] opened 2022-10-12 10:50 UTC
Since we moved to self-service topology, a deployment to production contains both the D365 platform/application and custom deployable package(s). What if a QU has been automatically deployed to the sandbox environment and a critical fix is due to be deployed to production. This would mean that the QU will be brought to production as well, although validation might still be pending from regression point-of-view...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment] 2022-10-14 09:17
Bug 758101 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:03
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:03 UTC
Labels: bug-created-VSTS
