### ISSUE TITLE
Unable to find "System administration > Periodic tasks > Database > Custom scripts" on my dev environment

### ISSUE THREAD

**Issue by artemt-yavica** [MicrosoftDocs/dynamics-365-unified-operations-public#4460] opened 2023-03-06 08:28 UTC
I am on  10.0.30 Update54, can't see "System administration > Periodic tasks > Database > Custom scripts" on my dev environment.
Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Version Independent ID: 2f09e8fa-e5dc-2e5d-3613-c6b4f6d7191a
* Content: [Run custom X++ scripts with zero downtime - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/run-custom-scripts)
* Content Source: [articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/deployment/run-custom-scripts.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @AndersGirke
* Microsoft Alias: **aevengir**

**Comment by bishalgoswami** [comment] 2023-03-06 10:17
Bug 796429 has been logged to address this issue.

**Comment by kamaybac** [comment] 2023-03-07 08:03
@artemt-yavica , I'm not sure why you're not seeing the path. The feature was released in version 10.0.25. I can open the page on my 10.0.33 environment. Maybe your user account is missing some permissions? (See  [Assign duties to users to control access](https://learn.microsoft.com/dynamics365/fin-ops-core/dev-itpro/deployment/run-custom-scripts#assign-duties-to-users-to-control-access))

**Comment by Alpa-Chino** [comment] 2023-03-10 08:58
On a dev VM you need a flight turned on to make the feature available. Run the following SQL script: INSERT INTO SYSFLIGHTING (FLIGHTNAME, ENABLED) VALUES('AppConsistencyCustomScriptFlight', 1)

**Comment by artemt-yavica** [comment] 2023-03-11 21:08
> On a dev VM you need a flight turned on to make the feature available. Run the following SQL script: INSERT INTO SYSFLIGHTING (FLIGHTNAME, ENABLED) VALUES('AppConsistencyCustomScriptFlight', 1)

Thanks, that worked!
I think this should be mentioned in the documentation.

**Comment by w-azure** [comment] 2024-04-09 21:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by w-azure** 2024-04-09 21:23 UTC
Labels: bug-created-VSTS, kfm-fx-devit
