### ISSUE TITLE
Documentation needs to be updated due to changes in the SqlPackage utility

### ISSUE THREAD

**Issue by dhand01** [MicrosoftDocs/dynamics-365-unified-operations-public#4278] opened 2022-11-16 19:07 UTC
[Enter feedback here]
Command line input has changed for SqlPackage. See Notes: https://techcommunity.microsoft.com/t5/azure-sql-blog/connection-security-improvements-in-sqlpackage-161/ba-p/3672758
It would be good to have this page updated, with guidelines on the correct way to use the new parameters at the command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5e8701-e1d4-25f8-d76a-ee7870b915e1
* Version Independent ID: 624211c7-2eb4-7154-d38f-236dc6f8f7a9
* Content: [Export a copy of the standard user acceptance testing (UAT) database - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat)
* Content Source: [articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/database/dbmovement-scenario-exportuat.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @laneswenka
* Microsoft Alias: **laswenka**

**Comment by bishalgoswami** [comment] 2022-11-16 19:49
Bug 769217 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:38
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:38 UTC
Labels: bug-created-VSTS
