### ISSUE TITLE
Fix incorrect method name GetAzureWritableUrl 

### ISSUE THREAD

**Issue by jpiquot** [MicrosoftDocs/dynamics-365-unified-operations-public#4131] opened 2022-08-23 09:18 UTC
Hi,

In the documentation, the name of the "GetAzureWriteUrl" method is incorrect. In some paragraphs, it's called "GetAzureWrit**abl**eUrl".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d963d4c-de1f-7730-bee2-016dcde40907
* Version Independent ID: 21b95d43-5ad9-0ffc-21b9-6a4ba9086a56
* Content: [Data management package REST API - Finance & Operations | Dynamics 365](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api)
* Content Source: [articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/data-entities/data-management-api.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment] 2022-08-23 09:32
Bug 734439 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 16:26
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 16:26 UTC
Labels: bug-created-VSTS
