### ISSUE TITLE
SysSetupConfigAttribute.Version is of type int

### ISSUE THREAD

**Issue by torbennehmer** [MicrosoftDocs/dynamics-365-unified-operations-public#4217] opened 2022-10-12 06:27 UTC
You are stating that "Version" can take a Major.Minor sequence. As of 10.0.27 at least this is incorrect, the class is implemented with the EDT "Version", which is a simple integer without any Array elements. So any version most probably has to be 0,1,2,3 etc. "4.5" (Real) would be converted to integer 4. When trying to do so, you indeed get the corresponding compiler warning:

Warning
The type conversion from 'real' to 'int(Version)' loses range and precision.

This is even wrong in the actual implementation of the Attrribute, which states "1.0" as a default value, thus even there a precision loss warning is probably being triggered.

Also, the chapter "Onboarding the X++ class to SysSetup" is ambigous: What does "once per version" mean. Is this the version number of the SysSetup class (hence, it'll run once and then never again in a given environment) or is this somehow reset per each D365 Plattform and/or application version?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55927241-9d0d-19f8-3e5a-a81184d387e6
* Version Independent ID: 55927241-9d0d-19f8-3e5a-a81184d387e6
* Content: [SysSetupConfigAttribute attribute - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/syssetupconfigattribute)
* Content Source: [articles/fin-ops-core/dev-itpro/dev-tools/syssetupconfigattribute.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/dev-tools/syssetupconfigattribute.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @josaw1
* Microsoft Alias: **najaidee**

**Comment by josaw1** [comment] 2022-10-17 19:59
@najaidee Please review. Thanks.

**Comment by johnmichalak** [comment] 2024-02-14 17:01
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:01 UTC
Labels: doc-bug, bug-created-VSTS
