### ISSUE TITLE
Proactive quality updates from Microsoft

### ISSUE THREAD

**Issue by ACHR9Q** [MicrosoftDocs/dynamics-365-unified-operations-public#4251] opened 2022-10-31 10:40 UTC
Regarding Proactive quality updates
 
•	No prior email and notifications regarding when and which environment will receive the Proactive quality updates. Instead, we only get 1 email when the quality update is completed.
•	No way to choose which environment will be updated during this first phase. No way to stop the update.
•	The support environment that needs to be exact replica of Production was updated without warning, now versions are different in prod and support, this might cause issues when trying to replicate issues from PROD in the support environment.
•	In the given document regarding Proactive quality updates, we got some dates based on the country region when the update was supposed to happen. The actual update was done on a completely different date.
•	We have multiple projects running in different regions in the same PROD environment, for this reason, we are only updating environments during weekends but now we cant choose when to get the Proactive quality updates.
•	Scania has Multiple LCS projects(25 sandbox environments, 50 developer machines, and 6 production environments), we are maintaining the same version everywhere and now with these Proactive quality updates, this is impossible to maintain.
•	**Would be much better to update all sandbox environments instead of a random one. We want to have either all updated or non at all to maintain the same version everywhere. We are not against Proactive quality updates. The big problem here is that only 1 environment, randomly chosen is getting updated. This is disrupting our whole version-handling process. Also, it is important for us to always have the SUPPORT and PROD environments on the same version. We should be given the possibility to skip the Proactive quality update for a specific environment.**
•	Our whole release flow is impacted because of this Proactive quality update.
•	As we have multiple LCS projects and environments actively working, we discuss with the business if they need the quality updated or if they will wait until the next service update. If they want the quality update we plan it, we communicate it and we update all environments based on the best downtime for the business.
•	From our perspective, this decision from Microsoft was taken without any consideration of how it can affect big customers like Scania. Basically, we do not accept this approach.

**We had a long discussion with support from MS, but they are helpless to do any help!!!!!**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by ACHR9Q** [comment] 2022-10-31 10:41
Regarding Proactive quality updates
 
•	No prior email and notifications regarding when and which environment will receive the Proactive quality updates. Instead, we only get 1 email when the quality update is completed.
•	No way to choose which environment will be updated during this first phase. No way to stop the update.
•	The support environment that needs to be exact replica of Production was updated without warning, now versions are different in prod and support, this might cause issues when trying to replicate issues from PROD in the support environment.
•	In the given document regarding Proactive quality updates, we got some dates based on the country region when the update was supposed to happen. The actual update was done on a completely different date.
•	We have multiple projects running in different regions in the same PROD environment, for this reason, we are only updating environments during weekends but now we cant choose when to get the Proactive quality updates.
•	Scania has Multiple LCS projects(25 sandbox environments, 50 developer machines, and 6 production environments), we are maintaining the same version everywhere and now with these Proactive quality updates, this is impossible to maintain.
•	Would be much better to update all sandbox environments instead of a random one. We want to have either all updated or non at all to maintain the same version everywhere. We are not against Proactive quality updates. The big problem here is that only 1 environment, randomly chosen is getting updated. This is disrupting our whole version-handling process. Also, it is important for us to always have the SUPPORT and PROD environments on the same version. We should be given the possibility to skip the Proactive quality update for a specific environment.
•	Our whole release flow is impacted because of this Proactive quality update.
•	As we have multiple LCS projects and environments actively working, we discuss with the business if they need the quality updated or if they will wait until the next service update. If they want the quality update we plan it, we communicate it and we update all environments based on the best downtime for the business.
•	From our perspective, this decision from Microsoft was taken without any consideration of how it can affect big customers like Scania. Basically, we do not accept this approach.

**Comment by bishalgoswami** [comment] 2022-10-31 12:27
Bug 761846 has been logged to address this issue.

**Comment by ACHR9Q** [comment] 2022-10-31 13:22
Hello, thank you for addressing this. That would be really great if we get a response soon.

**Comment by johnmichalak** [comment] 2024-02-14 17:27
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:27 UTC
Labels: bug-created-VSTS
