### ISSUE TITLE
Currently no way to know what was installed in a quality update

### ISSUE THREAD

**Issue by ApsiaCloud** [MicrosoftDocs/dynamics-365-unified-operations-public#4334] opened 2022-12-16 11:03 UTC
According to [how do i know what set of changes went into a quality update payload](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates#how-do-i-know-what-set-of-changes-went-into-a-quality-update-payload) the only way to get the content of a quality update is to check before its installation. So title of the section should be in futur tense, not preterit. 
And by the way, seems to be a good practice to have a release note and a way to retreive what was installed on an environment. So if you could offer this feature would really appreciate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Version Independent ID: 6edd9a5f-8212-173c-16fb-8868c5d4b4d9
* Content: [Proactive quality updates - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/quality-updates#schedule)
* Content Source: [articles/fin-ops-core/fin-ops/get-started/quality-updates.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/fin-ops/get-started/quality-updates.md)
* Service: **dynamics-365-cross-app**
* GitHub Login: @rashmansur
* Microsoft Alias: **rashmim**

**Comment by bishalgoswami** [comment] 2022-12-16 12:54
Bug 775322 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 20:24
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 20:24 UTC
Labels: bug-created-VSTS
