### ISSUE TITLE
What "valid" Power BI.com license is required for users

### ISSUE THREAD

**Issue by m-hanisch** [MicrosoftDocs/dynamics-365-unified-operations-public#4280] opened 2022-11-17 09:44 UTC
Sub heading [Things you must know before you start](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration#things-you-must-know-before-you-start) states the following
> Users navigating to these pinned tiles must have a valid Power BI.com license.

Could you be more precise in here please? What Power BI license is required for users in order to navigate to or rephrased consume pinned reports?
Power BI (free) license?
Power BI Pro license?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2213414-926d-10e1-538b-efef09dc0181
* Version Independent ID: 03be53f7-c305-cb02-7627-2ea4f1c01bd4
* Content: [Configure PowerBI.com integration - Finance & Operations | Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration)
* Content Source: [articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/main/articles/fin-ops-core/dev-itpro/analytics/configure-power-bi-integration.md)
* Service: **dynamics-365-cross-app**
* Product: ****
* Technology: ****
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **RICHDI**

**Comment by bishalgoswami** [comment] 2022-11-17 09:50
Bug 769398 has been logged to address this issue.

**Comment by johnmichalak** [comment] 2024-02-14 17:39
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by johnmichalak** 2024-02-14 17:39 UTC
Labels: bug-created-VSTS
